window.MARKER_DATABASE = window.MARKER_DATABASE || {};
window.mergeLanguageTexts = function () {
    const text_bundle_en = {
        '1TA.0.steps': {
            1: "kaidhaisEr pUmpozhil sUzh kachchi nagar * vandhudhiththa poygaippirAn kavigyar pOrERu * vaiyaththu adiyavargaL vAzha arum thamizh nURRandhAdhi * padi viLangachcheydhAn parindhu",
        },


        const text_bundle_en = {
            '1TA.1.steps': {
                1: " * vaiyam thagaLiyA vArkadalE neyyAga * veyya kadhirOn viLakkAga  *  seyyasudarAziyAn adikkE sUttinEn sol mAlai * idarAzhi nIngugavE enRu  ",
                2: "enRu kadal kadaindhadhu? evvulagam nIrERRadhu * onRum adhanai uNarEn nAn  *  anRuadhu adaiththu udaiththuk kaN paduththa Azhi * idhu nIpadaiththu idandhu uNdu umizhndha pAr  ",
                3: "pAraLavum Oradi vaiththu Oradiyum pAruduththa * nIraLavum sella nimirndhadhE  *  sUruruvinpEyaLavu kaNda perumAn! aRigilEn * nI aLavu kaNda neRi ",
                4: "neRivAsal thanE Ay ninRAnai *  aindhupoRivAsal pOrkkadhavam sAththi  *  aRivAnAmAla mara nIzhal aRam nAlvarkku anRu uraiththa * Alam amar kaNdaththu aran  ",
                5: "aran nAraNan nAmam An vidai puL Urdhi * urai nUl maRai uRaiyum kOyil  *  varai nIrkarumamazhippaLippuk kaiyadhu vEl nEmi  * uruvam eri kAr mEni onRu ",
                6: "onRu maRandhu aRiyEn Odha nIr vaNNanai nAn * inRu maRappanO EzhaigAL  *  anRukaruvarangaththuL kidhandhu kai thozhudhEn kaNdEn * thiruvarangamEyAn thisai  ",
                7: "thisaiyum thisaiyuRu dheyvamum *  dheyvaththisaiyum karumangaL ellAm  *  asaivil sIrkkaNNan nedumAl kadal kadaindha *  kArOdhavaNNan padaiththa mayakku ",
                8: "mayanga valampuri vAy vaiththu *  vAnathhuIyangum eri kadhirOn thannai *  muyangu amaruLthErAzhiyAl maRaiththadhu en?nI thirumAlE * pOrAzhik kaiyAl porudhu  ",
                9: "porukOttu Or EnamAyp pukku idandhAykku *  anRu unoru kOttin mEl kidandhadhanRE  *  virithOttasEvadiyai nItti thisai nadunga viN thuLanga * mAvadivin nI aLandha maN ",
                10: "maNNum malaiyum maRi kadalum mArudhamum * viNNum vizhungiyadhu meyyenbar *  eNNilalagu aLavu kaNda sIr AzhiyAykku *  anRu ivvulagu aLavu uNdO un vAy ",
                11: "vAy avanai alladhu vAzhththAdhu *  kai ulagamthAyavanai alladhu thAm thozhA *  pEy mulai nanjuUNAga uNdAn uruvodu pEr allAl  * kANA kaN kELa sevi ",
                12: "sevi vAy kaN mUkku udal enRu aimpulanum *  sendhIpuvi kAl nIr viN bUtham aindhum *  aviyAdhagyAnamum vELviyum nallaRamum enbarE * EnamAy ninRArkku iyalvu  ",
                13: "iyalvAga InthuzhAyAn adikkE sella * muyalvAr iyal amarar munnam *  iyalvAganIdhiyAl Odhi niyamangaLAl parava * AdhiyAy ninRar avar ",
                14: "Avar avar thAm thAm aRindhavARu Eththi * Ivar ivar em perumAn enRu *  suvar misaichchArththiyum vaiththum thozhuvar *  ulagaLandhamUrththi uruvE mudhal ",
                15: "mudhalAvAr mUvarE; am mUvaruLLum * mudhalAvAn mUri nIr vaNNan *  mudhalAyanallAn aruL allAl nAmanIr vaiyagaththu * pallAr aruLum pazhudhu  ",
                16: "pazhudhE pala pagalum pOyina enRu *  anjiazhudhEn aravaNai mEl kaNdu thozhudhEn * kadal Odham kAl alaippak kaNvaLarum *  sengaNadal Odha vaNNar adi  ",
                17: "adiyum padi kadappath thOL thisai mEl sella * mudiyum visumbu aLandhadhenbar *  vadi ugirAlIrndhAn iraNiyanadhu Agam *  irum siRaippuLUrndhAn ulagu aLandhanAnRu ",
                18: "nAnRa mulaiththalai nanjuNdu *  uRi veNNeythOnRa uNdAn venRi sUzh kaLiRRai UnRip * porudhudaivu uNdAnum puLLin vAy kINdAnum * marudhidai pOy maNNaLandha mAl  ",
                19: "mAlum karum kadalE ! en nORRAy? * vaiyagam uNduAlin ilaith thuyinRa AzhiyAn *  kOlakkarumEnich chengaN mAl kaN padaiyuL *  enRumthirumEni nI thINdap peRRu ",
                20: "peRRAr thaLai kazhalap pErndhu Or kuRaL uruvAych * cheRRAr padi kadandha sem kaN mAl  * naRRAmarai malarch chEvadiyai vAnavar kai kUppi * nirai malar koNdu EththuvarAl ninRu ",
                21: "ninRu nilam angai nIrERRu mUvadiyAl * senRu thisai aLandha sengaNmARku *  enRumpadai Azhi puLLUrdhi pAmbaNaiyAn pAdham * adaiyAzhi nenjE aRi ",
                22: "aRiyum ulagellAm yAnEyum allEn * poRi koL siRai uvaNam UrndhAy  * veri kamazhumkAmbEy menthoLi kadai veNNey uNdAyaith * thAmbE koNdu Arththa thazhumbu ",
                23: "thazhumbirundha sArnga nAN thOyndhavAm am kai * thazhumbirundha thAL sagadam sAdi *  thazhumbirundhapUngOdhaiyAL veruvap pon peyarOn mArvidandha * vIngOdha vaNNar viral  ",
                24: "viralOdu vAy thOyndha veNNey kaNdu *  AychchiuralOdu uRap piNindha nAnRu *  kuralOvAdhEngi ninaindhu ayalAr kANa irundhilaiyE * OngOdha vaNNA! urai  ",
                25: "uraimERkoNdu en uLLam OvAdhu *  eppOdhumvarai mEl maragadhamE pOla *  thirai mElkidandhAnaik kIndAnaik *  kEzhalAy bhUmiidandhAnai Eththi ezhum ",
                26: "ezhuvAr vidai koLvAr InthuzhAyAnai * vazhuvA vagai ninaindhu vaigal thozhuvAr * vinaich chudarai nandhuvikkum vEnkatamE *  vAnOrmanach chudaraith thUNdum malai ",
                27: "malaiyAl kudai kaviththu mAvAy piLandhu * silaiyAL marAmaram Ezh seRRu *  kolaiyAnaippOrkkOdu osiththanavum pUm kurundham sAyththanavum * kArkkOdu paRRiyAn kai ",
                28: "kaiya valampuriyum nEmiyum *  kArvaNNaththaiya malar magaL nin AgaththAL *  seyyamaRaiyAn ninnundhiyAn mAmadhiL mUnReydha * iRayAn nin Agaththu iRai ",
                29: "iRaiyum nilanum iru visumbum kARRum * aRai pulanum sem thIyum AvAn *  piRaimaruppinpaim kaN mAl yAnai padu thuyaram kAththaLiththa * sem kaN mAl kaNdAy theLi  ",
                30: "theLidhAga uLLaththaich chenniReei * gyAnaththeLidhAga nanguNarvAr sindhai *  eLidhAgaththAy nAdu kanRE pOl thaNduzhAyAn adikkE * pOy nAdikkoLLum purindhu ",
                31: "puriyoru kai paRRi, Or ponnAzhiyEndhi * ariyuruvum ALuruvumAgi  * eriuruvavaNNaththAn mArbidandha mAladiyai allAl *  maRRueNNaththAn AmO imai ",
                32: "imaiyAdha kaNNAl iruL agala nOkki * amaiyAp poRi pulangaL aindhum namaiyAmal * Agaththu aNaippAr aNaivarE *  Ayira vAynAgaththu aNaiyAn nagar ",
                33: "nagaram aruL purindhu nAn mugaRkup *  pUmElpagara maRai payandha paNban *  peyarinaiyEpundhiyAl sindhiyAdhu Odhi uru eNNum * andhiyAl Am payan angu en ",
                34: "ennoruvar meyyenbar EzhulaguNdu *  AlilaiyilmunnorovanAya mugil vaNNA *  nin urugippEyththAy mulai thandhAL pEndhilalAL *  pEramarkkaNAyththAy mulai thandhavARu ",
                35: "ARiya anbil adiyAr tham ArvaththAl * kURiya kuRRamAk koLLal nI thERi * nediyOy adi adaidhaRkanRE *  IraindhumudiyAn padaiththa muraN ",
                36: "muraNai vali tholaidhaRkAm enRE *  munnamtharaNi thanadhu AgaththAnE *  iraNiyanaippuNNirandha vaL ugirAl pon AzhikkaiyAl *  nImaNNirandhu koNda vagai  ",
                37: "vagaiyaRu nuN kELvi vAyvArgaL *  nALumpugai viLakkum pUm punalum Endhi *  thisaithisaiyilvEdhiyargaL senRu iRainjum vEnkatamE *  veN sangamUdhiya vAy mAl ugandha Ur ",
                38: "Urum vari aravam oN kuRavar mAL yAnai * pEra eRindha peru maNiyai *  kArudaiyamin enRu puRRadaiyum vEnkatamE *  mEla surarem ennum mAladhu idam  ",
                39: "idandhadhu bhUmi eduththadhu kunRam * kadandhadhu kanjanai mun anja *  kidandhadhuvumnIrOdha mA kadalE ninRadhuvum vEnkatamE * pErOdha vaNNar peridhu ",
                40: "peruvil pagazhik kuRavar kaichchendhI * veruvip punam thuRandha vEzham *  iruvisumbilmIn vIzhak kaNdu anjum vEnkatEmE *  mEl asurarkOn vIzhak kaNdu ugandhAn kunRu ",
                41: "kunRu anaiya kuRRam seyyinum guNam koLLum * inRu mudhalAga en nenjE *  enRumpuRan uraiyE Ayinum pon Azhik kaiyAn * thirRn uraiyE sindhiththu iru ",
                42: "thirumagaLum maNmagaLum AymagaLum sErndhAl * thirumagatkE thIrndhavARu enkol *  thirumagaL mElpAl Odham sindhap pada nAgaNaik kidandha * mAlOdha vaNNar manam ",
                43: "manamAsu thIrum aruvinaiyum sArA * dhanamAya thane kaikUdum *  punamEyapUnthuzhAyAn adikkE pOdhodu nIr Endhi * thAm thozhA niRpAr thamar ",
                44: "thamar ugandhadhu evvuruvam avvuruvam thAnE * thamar ugandhadhu eppEr maRRu appEr *  thamar ugandhuevvaNNam sidhiththu imayAdhu irupparE * avvaNNam AzhiyAnAm  ",
                45: "AmE amararkku aRiyavadhu niRka * nAmE aRigiRpOm nannenjE *  pUmEyamAdhavaththOn thAL paNindha vALarakkan nINmudiyai * pAdhamaththAl eNNinAn paNbu ",
                46: "paN purindha nAnmaRaiyOn sennip paliyERRa * veNpurinUl mArban vinai thIra *  puN purindhaAgaththAn thAL paNivAr kaNdIr *  amarar thambhOgaththAl bhUmi ALvAr ",
                47: "vAri surukki madhak kaLiRu aindhinaiyum * chEri thiriyAmal senniRIi *  kUriyamey gyAnaththAl uNarvAr kANbarE *  mEl oru nALkai nAgam kAththAn kazhal ",
                48: "kazhal onRu eduththu oru kai suRRi Or kai mElsuzhalum surAsurargaL anja *  azhalumseruvAzi EndhinAn sEvadikkE sella * maruvAzhi nenjE magizh ",
                49: "magizh alagu onRE pOl mARum pal yAkkai * negizha muyalgiRpArkkallAl *  mugizh virindhasOdhi pOl thOnRum sudar pon nedu mudi *  emAdhi kANbArkkum aridhu ",
                50: "ariya pulan aindhadakki Ay malar koNdu * Arvampuriya parisinAl pulgil  * periyanAymARRAdhu vIRRirundha mAvalipAl *  vaNkai nIrERRAnaik kAnbadhu eLidhu ",
                51: "eLidhil iraNdadiyum kANbadhaRku *  ennuLLamtheLiyath theLindhozhiyum sevvE *  kaLiyilporundhAdhavanaip poraluRRu *  ariyAyirundhAn thirunAmam eN ",
                52: "eNmar padhinoruvar IraRuvar Oriruvar * vaNNa malar Endhi vaigalum *  naNNioru mAlaiyAl paravi OvAdhu *  eppOdhumthirumAlaik kai thozhuvar senRu ",
                53: " * senRAl kudaiyAm irundhAl singAsanamAm * ninRAl maravadiyAm nIL kadaluL *  enRumpuNaiyAm maNiviLakkAm pUm pattAm pulgumaNaiyAm *  thirumARku aravu ",
                54: "aravam adal vEzham An kurundham puL vAy * kuravai kuda mulai maRkunRam *  karavinRivittiRuththu mEyththosiththu kIndu kOththAdi * uNduatteduththa sem kaN avan ",
                55: "avan thamar evvinaiyar Agilum *  engOnavan thamarE enRu ozhivadhallAl *  naman thamarAlArAyappattum aRiyAr kaNdIr *  aravaNai mElpErAyaRku AtpattAr pEr ",
                56: "pErE varap pidhaRRal allAl em pemmAnai * ArE aRivAr adhu niRka *  nErEkadikkamalaththuL irundhum kANgilAn *  kannanadikkamalam thannai ayan ",
                57: "ayal ninRa valvinaiyai anjinEn; anjiuya nin thiruvadiyE sErvAn *  naya ninRananmAlai koNdu namO nAranA ennum * sonmAlai kaRREn thozhudhu ",
                58: "thozudhu malar koNdu dhUpam kai Endhi * ezhudhum; ezhu, vAzhi nanjE! *   pazhudhinRimandhirangaL kaRpanavum mAladiyE kai thozhuvAn * andharam onRu illai adai ",
                59: "adaindha aruvinaiyOdu allal nOy pAvam * midaindhu avai mINdozhiya vENdil *  nudangidaiyaimunnilangai vaiththAn muraN azhiya *  munnoru nALthanvilangai vaiththAn charaN ",
                60: "charaNA maRai payandha thAmaraiyAnOdu * maraNAya mannuyirgatkellAm *  araNAyapErAzhi koNda pirAn anRi maRRu aRiyAdhu * OrAzhi sUzhndha ulagu ",
                61: "ulagum ulagiRandha Uzhiyum *  oNkEzhvilagu karungadalum veRpum *  ulaginilsendhIyum mArudhamum vAnum *  thirumAlthanpundhiyilAya puNarppu ",
                62: "puNar marudhinUdu pOyp pUngurundham sAyththu * maNam maruva mAl vidai Ezh seRRu *  kaNam veruvaEzhulagum thAyanavum eNdhisaiyum pOyinavum * sUzharavap pongaNaiyAn thOL ",
                63: "thOL avanai allAl thozhA *  en sevi iraNdumkEL avanadhu inmozhiyE kEttirukkum *  nAnALumkONAgaNaiyAn kurai kazhalE kURuvadhE * nANAmai naLLEn nayam ",
                64: "nayavEn piRar poruLai, naLLEn kIzhArOdu * uyavEn uyarndhavarOdu allAl  *  viyavEnthirumAlai alladhu dheyvam enRu EththEn * varumARu en enmEl vinai ",
                65: "vinaiyAL adarppadAr vennaragil sErAr * thinaiyEnum thIkkadhikkaN sellAr *  ninaithaRkariyAnaich chEyAnai *  Ayiram pEr sengatkariyAnaik kai thozhudhakkAl ",
                66: "kAlai ezhundhu ulagam kaRpanavum *  kaRRuNarndhamElaith thalaimaRaiyOr vEtpanavum *  vElaikkaNOrAzhiyAn adiyE; Odhuvadhum Orppanavum * pErAzhi koNdAn peyar ",
                67: "peyarum karum kadalE nOkkum ARu *  oNpUuyarum kadhiravanE nOkkum *  uyirumdharumanaiyE nOkkum oN thAmaraiyAL kELvan * oruvanaiyE nOkkum uNarvu ",
                68: "uNarvAr Ar un perumai? UzhidhORUzhi * uNarvAr Ar un uruvam thannai? *  uNarvAr ArviNNagaththAi ! maNNagaththAi ! vEngadaththAi ! *  nAlvEdhappaNNagaththAi nI kidandha pAl ",
                69: "bAlan thanadhu uruvAy? EzhulaguNdu *  AlilaiyinmEl anRu nI vaLarndha mey enbar *  AlanRuvElai nIr uLLadhO? viNNadhO? maNNadhO? * sOlai sUzh kunRu eduththAy sollu ",
                70: "sollum thanaiyum thozhumin, vizhum udambu * sellum thanaiyum thirumAlai *  nal idhazhththAmaththAl vELviyAl thandhiraththAl mandhiraththAl * nAmaththAl EththudhirEl nanRu ",
                71: "nanRu piNi mUppuk kaiyagaRRi nAngUzhi * ninRu nilam muzhudhum ANdAlum *  enRumvidal Azhi nenjamE vENdinEn kaNdAy * adal Azhi koNdAn mAttu anbu ",
                72: "anbAzhiyAnai aNugennum *  nA avanthanpaNbAzhith thOL paravi Eththennum *  munbUzhikANAnaik kAn ennum kaN sevi kEL ennum * pUNAram pUNdAn pugazh ",
                73: "pugazhvAy pazhippAy nI pUndhuzhAyAnai * igazhvAy karudhuvAy nenjE! *  thigazhnIrkkadalum malaiyum iruvisumbum kARRum * udalum uyirum ERRAn ",
                74: "ERRAn, puLLUrndhAn; eyil eriththAn, mArvidandhAn * nIRRAn, nizhalmaNi vaNNaththAn *   kURRorupAlmangaiyAn, pUmagaLAn, vArsadaiyAn, nIlmudiyAn * gangaiyAn,nILkazhalAn kAppu  ",
                75: "kAppunnai unnak kazhiyum ;aruvinaigaL * Appunnai unna avizhndhu ozhiyum  * mUppu unnaichchindhippArkkillai thirumAlE  * nin adiyaivandhippAr kANbar vazhi ",
                76: "vazhi ninRu ninnaith thozhuvAr *  vazhuvAmozhi ninRa mUrththiyarE Avar *  pazhudhonRumvArAdha vaNNamE viN kodukkum *  maNNaLandhasIrAn thiruvEngadam ",
                77: "vEngadamum viNNagarum vehkAvum *  ahkAdhapUngidangin nIL kOval ponnagarum *  nAngidaththumninRan irundhAn kidandhAn nadandhAnE * enRAl kedumAm idar ",
                78: "idar Ar paduvAr? ezhu nenjE ! *  vEzhamthodarvAn kodu mudhalai sUzhndha *  padamudaiyapainnAgap paLLiyAn pAdhamE kai thozhudum * koinnAgap pUm pOdhu koNdu ",
                79: "koNdArai allAl koduththArai yAr pazhippAr * maN thA ena irandhu mAvaliyai *  oN thArainIr am kai thOya nimirndhilaiyE? *  nIL visumbilAr am kai thOya aduththu ",
                80: "Aduththa kadum pagaigyaRku ARREn enROdi * paduththa perum pAzhi sUzhndha vidaththaravai * vallALan kai koduththa mAmEni mAyavanukku * allAdhum AvArO AL ",
                81: "ALamar venRi adu kaLaththuL agyAnRu * vALamar vENdi varai nattu *  nILaravaichchuRRik kadaindhAn peyar anRE? *  thol nagaraippaRRIk kadaththum padai ",
                82: "padaiyArum vAL kaNNAr pArasinAL *  paimpUmthodaiyalOdu Endhiya dhUpam *  idaiyidaiyilmIn mAya mAsUNum vEngadamE *  mEl orunALmAn mAya eydhAn varai ",
                83: "varai kudai thOL kAmbAga Anirai kAththu *  Ayarnirai viadai Ezh seRRavARu ennE *  uravudaiyanIrAzhi uL kidandhu nErA nisAsarar mEl * pErAzhi koNda pirAn ",
                84: "pirAn! un perumai piRar Ar aRivAr? * urAy ulagu aLandha gyAnRu *  varAgaththueyiRRaLavu pOdhAvARu enkolO? *  endhaiadikkaLavu pOndha padi ",
                85: "padi kaNdu aRidhiyE pAmbaNaiyinAn *  puLkodi kaNdu aRidhiyE kURAy *  vadivilpoRi aindhum uLLadakki pOdhodu nIr Endhi * neRi ninRa nenjamE! nI ",
                86: "nIyum thirumagaLum ninRAyAl  * kunRu eduththuppAyum pani maRuththa paNbALA  * vAsalkadai kazhiyA uL pugAk kAmar pUm kOval * idai kaziyE paRRi, ini ",
                87: "iniyAr puguvAr ezhu naraga vAsal? * muniyAdhu mUriththAL kOmin *  kanisAyakkanRu eRindha thOLAn kanai kazhalE kANbadhaRku * nangaRindha nAvalam sUzh nAdu ",
                88: "nAdilum ninnadiyE nAduvan *  nAdORumpAdilum nin pugazhE pAduvan *  sUdilumpon Azhi EndhinAn ponnadiyE sUduvERku * ennAgil ennE enakku ",
                89: "enakkAvAr Ar oruvarE  * em perumAnthankkAvAn thanE maRRallAl  * punakkAyAmpUmEni kANapp podhiyavizhum pUvaippU * mAmEni kAttum varam ",
                90: "varaththAl vali ninaindhu mAdhava! nin pAdham * siraththAl vaNangAnAm enRE? *  uraththinAlIrariyAy nEr valiyOnAna iraNiyanai * Or ariyAl nI idandhadhu Un ",
                91: "Unak kurumbaiyin uL pukku iruL nIkki * gyAnach chudar koLIi nAL dhORum *  EnaththuuruvAy ulagu idandha UzhiyAn pAdham * maruvAdhArkku uNdAmO vAn ",
                92: "vAnAgith thIyAy maRi kadalAy mArudhamAy * thEnAgip pAlAm thirumAlE *  AnAychchiveNNey vizhunga niRaiyumE *  munnorunALmaNNai umizhndha vayiRu ",
                93: "vayiRu azhala vALuruvi vandhAnai anja * eyiRu ilaga vAy maduththadhu en nI? *  poRi ugirAlpU vadivai Idu azhiththa pon Azhik kaiyA ! *  ninsEvadimEl Idazhiyach cheRRu ",
                94: "seRRezhundhu thIvizhiththuch chenRa indha Ezhulagum * maRRivaiyA enRu vAy angAndhu *  muRRummaRaiyavarkkuk kAttiya mAyavanai allAl * iRaiyEnum EththAdhu en nA ",
                95: "nA vAyil uNdE; namO nAraNA enRu, * OvAdhu uraikkum urai uNdE *  mUvAdhamAkkadhikkaN sellum vagai uNdE *  en oruvarthIkkadhikkaN sellum thiRam ",
                96: "thiRambAdhen nenjamE sengaNmAl kaNdAy * aRam pAvam enRu iraNdum AvAn *  puRandhAn immaNdhAn maRi kadaldhAn mArudhandhAn *  vAndhAnEkaNdAy kadaikkat pidi ",
                97: "pidi sEr kaLiRaLiththa pErALA !  *  un thanadi sErndhu aruL peRRAL anRE *  podi sEranaR gangai ERRAn avirsadaimEl pAyndha * punaR gangai ennum pErp pon ",
                98: "pon thigazhum mEnip purisadai am puNNiyanum * ninRu ulgam thAya nedumAlum *  enRumiruvar angaththAl thirivarElum *  oruvanoruvan angaththenRum uLan ",
                99: " * uLan kaNdAy nannenjE! uththaman enRumuLan kaNdAy *  uLLuvAr uLLaththu uLan kaNdAy * veLLaththin uLLAnum vEngadaththu mEyAnum * uLLaththin uLLAn enRu Or ",
                100: " * Oradiyum sAdudhaiththa oN malarch chEvadiyum * Iradiyum kANalAm en nenjE ! *  OradiyilthAyavanaik kEsavanaith thaNduzhAy mAlai sEr * mAyavanaiyE manaththu vai",

            },
        };

        // Non-destructive runtime merging engine
        for(const key in text_bundle_en) {
            window.MARKER_DATABASE[key] = window.MARKER_DATABASE[key] || [];
            for (const p in text_bundle_en[key]) {
                const idx = parseInt(p) - 1;
                window.MARKER_DATABASE[key][idx] = window.MARKER_DATABASE[key][idx] || { p: parseInt(p) };
                window.MARKER_DATABASE[key][idx]['text'] = window.MARKER_DATABASE[key][idx]['text'] || {};
                window.MARKER_DATABASE[key][idx]['text']['en'] = text_bundle_en[key][p];
            }
        }
    };
