window.MARKER_DATABASE = window.MARKER_DATABASE || {};
window.mergeLanguageTexts = function () {
    const text_bundle_en = {
        '3TA.0.steps': {
            0: "SeerArum mADa tirukkOvaloor adanuLkArAr karu mugilai kANa pukku OrA * tirukkaNDEn enru uraitta SeerAn kazhalEurai kaNDAi nenjE ugandu * ",
        },
        '3TA.1.steps':
        {
            1: "tirukkaNDEn ponmEni kaNDEn tihazhumarukkan aNi niramum kaNDEn serukkiLarum* ponnAzhi kaNDEn purisangu angai kaNDEnennAzhi vaNNan pAl inru * ",
            2: "inrE kazhal kaNDEn Ezhpirappum yAnaruttEnpontOi varai mArbil poonduzhAi anru * tirukkaNDu koNDa tirumAlE unnaimarukkaNDu koNDu en manam * ",
            3: "manattuLLAn mAkaDal neeruLLAn malarALtanattuLLAn taNDuzhAi mArban sinattu * serunar uha seRRuganda tEngOda vaNNanvaru naraham teerkkum marundu * ",
            4: "marundum poruLum amudamum tAnEtirundiya sengaNmAl AngE porundiya * ninrulahamuNDu umizhndu neerERRu moovaDiyAlanrulaham tAyOnaDi * ",
            5: "aDivaNNam tAmarai anrulagam tAyOnpaDivaNNam pArkkaDal neervaNNam muDivaNNam * OrAzhi veyyOn oLiyumaKdanrEArAzhi koNDArkku azhahu * ",
            6: "azhaganrE AzhiyArku Azhineer vaNNamazhaganrE aNDam kaDattal azhaganrE * angai neerERRArku alarmElOn kAlkazhuvagangaineer kAnra kazhal * ",
            7: " kazhaltozhudum vAnenjE kArkkaDalneer vElaipozhilaLanda puLLoordi selvan ezhilaLandu * eNNarkariyAnai epporuTkum sEyAnainaNNarkariyAnai nAm * ",
            8: "nAmam palasolli nArAyaNa enrunAm angaiyAl tozhudum nannenjE vA maruvi * maNNulaham uNDumizhnda vaNDaraiyum taNDuzhAikaNNanaiyE kANga nan kaN * ",
            9: "kaNNum kamalam kamalamE kaittalamummaNNaLanda pAdamum maRRavaiyE eNNir * karumA muhil vaNNan kArkkaDal neer vaNNantirumAmaNi vaNNan tESu",
            10: "tEsum tiralum tiruvum uruvummAsil kuDipirappum maRRavaiyum pEsil * valampurindu vAn sangam koNDAn pErOdanalam purindu senraDaiyum nangu * ",
            12: "arivennum tALkOLuvi aimpulanum tammilserivennum tiNkadavam semmi maraiyenrum * nangOdi nanguNarvAr kANbarE nADOrumpaingOda vaNNan paDi * ",
            13: "paDivaTTa tAmarai paNDulagam neerERRuaDivaTTatAl aLappa neeNDa muDivaTTam * AgAyam ooDaruttu aNDam pOi neeNDadEmAgAyamAi ninra mArku * ",
            14: "mArpAl manamsuzhippa mangaiyartOL kaiviTTunoorpAl manam vaikka noividAm nArpAla * vEdattAn vEngaDattAn viNNOr muDitOyumpAdattAn pAdam paNindu * ",
            15: "paNinduyarnda bouva paDutiraigaL mOdapaNinda paNa maNihaLAlE aNindangu * anandan aNai kiDakkum ammAn aDiyEnmanandan aNai kiDakkum vandu * ",
            16: " vandudaitta veNDiraigaL sembavaLa veNmuttamandiviLakkum aNi viLakkAm endai * oruvalli tAmaraiyAL onriyaseer mArbantiruvallikkENiyAn senRu * ",
            17: "senranAL sellAda sengaNmAlengaL mAlenra nALennALum nALAhum enrum * iravAda endai iNaiyaDikkE ALAimaravAdu vAzhttuhaven vAi * ",
            18: "vAimozhindu vAmananAi mAvalipAl moovaDimaNneeyaLandu koNDa neDumAlE tAviya nin * enjA iNaiyaDikkE EzhpirappumALAgianjAdirukka aruL * ",
            19: "aruLAdozhiyumE AlilaimEl anruteruLAda piLLaiyAi sErndAn iruLAda * sindaiyarAi sEvaDikkE semmalar tooi kaittozhudumundaiyarAi nirpArkku mun * ",
            20: "munnulagam uNDu umizhndAikku avvulagam eeraDiyAl pinnaLandu kODal peridonrE ennE * tirumAlE sengaNeDiyAnE engaLperumAnE neeyidanai pEsu * ",
            21: "pEsuvAr evvaLavu pEsuvar avvaLavEvAsamalar tuzhAi mAlaiyAn tEsuDaiyachakkarattAn sanginAn sArngattAn pongaravavakkaranai konrAn vaDivu * ",
            22: "vaDivAr muDikOTTi vAnavargaL nALumkaDiyAr malartoovi kANum paDiyAnai * semmaiyAluLLurugi sevvanE nenjamEmeimmeyE kANa virumbu * ",
            23: "virumbiviN maNNaLanda anjiraiya vaNDArsurumbu tuLaiyil senrooda arumbum * punanduzhAi mAlaiyAn ponnangazharkEmananduzhAi mAlAi varum * ",
            24: "varungAlirunilanum mAlvisumbum kARRumnerungutee neer uruvumAnAn porundum * suDarAzhi onruDaiyAn SoozhkazhalE nALumtoDarAzhi nenjE tozhudu * ",
            25: "tozhudAl pazhuduNDE? tooneerulahammuzhuduNDu moikuzhalALAichchi vizhuduNDa * vAyAnai mAlviDaiyEzh seRRAnai vAnavarkkumsEyAnai nenjE sirandu * ",
            26: "sirandaven sindaiyum sengaNaravumniraindaseer neeLkachchiyuLLum uraindaduvum * vEngaDamum vehKAvum vELukkai pADiyumEtAngaDavAr taNDuzhAyAr * ",
            27: "ArE tuyaruzhandAr tunbuRRAr ANDaiyArkArEmalinda karungaDalai nErE * kaDaindAnai kAraNanai neeraNaimEl paLLiaDaindAnai nALumaDaindu * ",
            28: "aDainda aravaNai mEl aivarkkAi anrumiDaindadu bAradavempOr uDaindaduvum * AichchipAl mattukkE ammanE! vALeyiRRupEichchipAluNDa pirAn * ",
            29: "pEichchipAluNDa perumAnai pErndeDuttuAichchimulai koDuttAL anjAdE vAitta * iruLAr tirumEni in pavaLa sevvAiteruLA mozhiyAnai sErndu * ",
            30: " sErnda tirumAl kaDal kuDandai vENgaDamnErnda vensindai niraivisumbum vAinda * maraipADaham anandan vaNDuzhAi kaNNiiraipADi Aya ivai * ",
            31: "ivai avan kOyil iraNiyanadu Ahamavai seidu ari uruvamAnAn seviteriyA * nAhattAn nAlvEdattu uLLAn naravERRAnbAgattAn pArkaDaluLAn * ",
            32: "pArkaDalum vEngaDamum pAmbum panivisumbumnoorkaDalum nuNNoola tAmaraimEl pArpaTTu * irundAr manamum iDamAha koNDAnkurundositta gOpAlagan * ",
            33: "bAlaganAi AlilaimEl paiya ulahellAmmElorunALuNDavanE meimmeiyE mAlavanE * mandarattAl mAneerkkaDal kaDaindu vAnamudamandarattArkku eendAinee anru * ",
            34: "anru ivvulagam aLanda asavE kolninrirundu vELukkai neeNagarvAi anru * kiDandAnai kEDil neerAnai mun kanjaikaDandAnai nenjamE kAN * ",
            35: "kANkANena virumbum kaNgaL kadirilahupooNDAr ahalattAn ponmEni pAN kaNtozhil pADi vaNDaraiyum tongalAn semborkazhal pADi yAm tozhudum kai * ",
            36: "kaiya kanalAzhi kArkkaDalvAi veNsangamveyyagadai shArngam venjuDarvAL seyya * paDaiparavai pAzhi panineerulagamaDiyaLanda mAyar avarkku * ",
            37: "avarkkaDimai paTTEn agattAn purattAnuvarkkum karungaDal neeruLLAn tuvarkkum * pavaLavAi poomagaLum panmaNi pooNAramtigazhum tirumArvan tAn * ",
            38: " tAnE tanakku uvaman tannuruvE evvuruvumtAnE tava uruvum tArahaiyum tAnE * erisuDarum mAlvaraiyum eNDiSaiyum aNDattuirusuDarum Aya irai * ",
            39: "iraiyAi nilanAgi eNDiSaiyum tAnAimaraiyAi maraiporuLAi vAnAi piraivAinda * veLLattaruvi viLangolineer vEngaDattAnuLLattinuLLE uLan * ",
            40: "uLankaNDAi nannenjE uttaman enrumuLankaNDAi uLLuvAruLLattu uLankaNDAi * viNNoDunga kODuyarum veengaruvi vEngaDattAnmaNNoDunga tAnaLanda man * ",
            41: "mannu maNi muDi neeNDu aNDampOi eNDiSaiyumtunnu pozhil anaittum soozhkazhalE minnai * uDaiyAha koNDu anrulagaLandAn kunramkuDaiyAga A kAtta kO * ",
            42: "kOvalanAi AniraigaL mEittu kuzhaloodimAvalanAi keeNDa maNi vaNNan mEvi * ariyuruvamAgi iraNiyanadu Ahamteri ugirAl keeNDAn sinam * ",
            43: "sinamA madakaLiRRin tiNmaruppai sAittupunamEya boomiyadanai danamAga * pEragalattu uLLoDukkum pErAra mArvanArOragalattuLLadu ulagu * ",
            44: "ulagamum oozhiyum Azhiyum oNkEzhalarkadirum sendeeyum AvAn palakadirgaL * pAritta paimbon muDiyAnaDiyiNaikkEpooritten nenjE puri * ",
            45: "purindu madavEzham mAppiDiyODu ooDitirindu sinattAl porudu virindaseer * veNkOTTu muttudirkkum vEngaDamE mElorunALmaNkOTTu koNDAn malai * ",
            46: "malai mugaDu mElvaittu vAsukiyai suRRitalaimuhaDu tAnorukai paRRi alaimuhaTTu * aNDam pOi neerterippa anrukaDal kaDaindAnpiNDamAi ninra pirAn * ",
            47: "ninra perumAnE neerERRu ulagellAmsenra perumAnE sengaNNA anru * turagavAikeeNDa tuzhAi muDiyAi nangaLnarakavAy keeNDAyum nee * ",
            48: "neeyanrE neerERRu ulagamaDi aLandAineeyanrE ninRu niraimEittAi neeyanrE * mAvAyuram piLandu mAmarudinooDu pOidEvAsuram porudAi seRRu * ",
            49: "seRRaduvun sErA iraNiyanai senrERRupeRRaduvum mAnilam pinnaikkAi muRRal * muriyERRin munninru moimbozhittAi moorisuriyEru sanginAi soozhndu * ",
            50: "soozhnda tuzhAi alangal sOdi maNimuDimAltAzhnda aruvi taDaivaraivAi Azhnda * maNineer sunaivaLarnda mAmudalai konrAnaNineela vaNNattavan * ",
            51: "avanE aruvaraiyAl AniraigaL kAttAnavanE aNimarudam sAittAn avanE * kalangA peru naGaram kATTuvAn kaNDeerilangApuram erittAn eidu * ",
            52: " eidAn marAmaram EzhumirAmanAieidAn ammAn mariyai EndizhaikkAi eidaduvum * tennilangai kOn veezha senru kuraLuruvAimunnilam kaikkoNDAn muyanru * ",
            53: "muyanru tozhunenjE moorineer vElaiiyanra marattu AlilaiyinmElAl payinrangOr * maNNalangoL veLLattu mAya kuzhaviyAitaNNalangal mAlaiyAn tAL * ",
            54: "tALAl sagaDam udaittu pagaDundikeeLA marudiDaipOi kEzhalAi meeLAdu * maNNagalam keeNDangOr mAduganda mArvarkupeNNagalam kAdal peridu * ",
            55: " periya varaimArvil pErAram pooNDukariya muhiliDai min pOla tiriyungAl * pANoDunga vaNDaraiyum pangayamE maRRavantanneeNeDungaN kATTum niram * ",
            56: "niram veLidu seidu pasidu karidenruiraiyuruvam yAmariyOm eNNil niraivuDaiya * nAmangai tAnum nalampugazha vallaLEpoomangai kELvan polivu * ",
            57: "polindiruNDa kArvAnil minnEpOl tOnrimalindu tiruvirunda mArvan polinda * garuDan mEl koNDa kariyAn kazhalEteruL tan mEl kaNDAi teLi * ",
            58: "teLinda silAtalattin mElirunda mandiaLinda kaDuvanaiyE nOkki viLangiya * veNmadiyam tAvennum vEngaDamE mElorunALmaNmadiyil koNDugandAn vAzhvu * ",
            59: "vAzhum vagaiyarindEn maipOl neDuvaraivAitAzhumaruvi pOl tArkiDappa soozhum * tirumAmaNi vaNNan sengaNmAl engaLperumAnaDi sEra peRRu * ",
            61: "paNDellAm vEngaDam pArkaDal vaikundamkoNDangu uraivArkku kOyil pOl vaNDu * vaLangiLarum neeL sOlai vaNpoongaDigaiiLangumaran tan viNNagar * ",
            62: "viNNagaram vehKa viritiraineer vEngaDammaNNaharam mAmADa vELukkai maNNagatta * tenkuDandai tEnAr tiruvarangam tenkOTTitankuDangai neerERRAn tAzhvu * ",
            63: "tAzh saDaiyum neeNmuDiyum oNmazhuvum chakkaramumsoozharavum ponnANum tOnrumAl soozhum * tiraNDaruvi pAyum tirumalaimEl endaikkuiraNDuruvum onrAi isaindu * ",
            64: "isainda aravamum veRpum kaDalumpasaindu angamudu paDuppa asaindu * kaDainda varuttamO kachchi vekkAvilkiDandirundu ninraduvum angu * ",
            65: " angar kiDarinri andi pozhudattumanga iraNiyanadAhattai pongi * ariyuruvamAi piLanda ammAnavanEkariyuruvam kombosittAn kAindu * ",
            66: "kAindiruLai mARRi kadirilagu mAmaNigaLEinda paNakkadirmEl vevvuyirppa vAinda * madukaiTabarum vayiruruhi mANDAradukEDavarkku irudi Angu * ",
            67: "Angumalarum kuviyumAlundi vAiOngu kamalattinoNpOdu Angai * tigirisuDarenrum veNsangam vAnilpagarum madi enrum pArttu * ",
            68: "pArtta kaDuvan sunaineer nizharkaNDupErttOr kaDuvanena pErndu kArtta * kaLanganikku kaineeTTum vEngaDamE mEnALviLanganikku kanrerindAn veRpu * ",
            69: "verpenru vEngaDam pADum viyan tuzhAikarpenru sooDum karunguzhal mEl marponra * neeNDatOL mAl kiDanda neeL kaDal neerADuvAnpooNDanAL ellAm puhum * ",
            70: "pugumadattAl vAipoosi keezhtAzhndu aruviugumadattAl kAlkazhuvi kaiyAl migumadatten * viNDamalar koNDu viral vEngaDavanaiyEkaNDu vaNangum kaLiru * ",
            71: "aLiru mugil kutta kaiyeDuttODioLiru marupposikaiyALi piLiri * vizha konru ninradirum vEngaDamE mEnALkuzhakkanru koNDerindAn kunRu * ",
            72: "kunronrinAya kuramahaLir kOl vaLaikkaisenru viLaiyADum teengazhaipOi venru * viLangumadi kOLviDukkum vEngaDamE mElaiiLangumarar kOmAniDam * ",
            73: "iDam valam Ezh pooNDa iravitErOTTivaDamuha vEngaDattu mannum kuDanayanda * kootatnAi ninrAn kuraikazhalE kooruvadEnAttanAluLLa nalam * ",
            74: "alamE validukol nanjooTTu vanpEinilamE puraNDu pOi veezha salamEdAn * vengongai uNDAnai meeTTAichchi ooTTuvAntankongai vAivaittAL sArndu * ",
            75: "sArndu agaDu tEippa taDAviya kOTTuchchivAioorndiyangum vaNmadiyin oN muyalai sErndu * sinavEngai pArkkum tirumalaiyE AyanpunavEngai nArum poruppu * ",
            76: "poruppiDaiyE ninrum punal kuLittum ainduneruppiDaiyE nirkavum neer vENDA viruppuDaiya * vehKAvE sErndAnai meimmalartooi kaitozhudAlaKAvE teevinaigaL Aindu * ",
            77: "Ainda varumaraiyOn nAnmugattOn nangurangilvAinda kuzhaviyAi vALarakkan Einda * muDippOdu moonrEzhenreNNinAn ArndaaDippOdu nangaTku araN * ",
            78: "araNAm namakkenrum Azhi valavanmuranAL valam suzhinda moimban saraNAmEl * Edugadi Edu nilai Edu pirappennAdEOdugadi mAyanaiyE Orttu * ",
            79: "Ortta manattarAi aindaDakki ArAindupErttAl pirappEzhum pEikkalAm kArtta * viraiyAr narunduzhAi veengOda mEniniraiyAra mArvanaiyE ninRu * ",
            80: " ninredirAya niraimaNittEr vANan tOLonriya veerainooruDan tuNiya venrilangum * ArpaDuvAn nEmiyaravaNaiyAn sEvaDikkEnErapaDuvAn tAn muyalum nenju * ",
            81: "nenjAl ninaipariyanElum nilaipeRREnnenjamE pEsAi ninaikkungAl nenjattu * pErAdunirkum perumAnai en kolOOrAdu nirpadu uNarvu * ",
            82: "uNaril uNarvariyan uLLam puhundupuNarilum kANbariyan uNmai iNaraNaiya * kongaNaindu vaNDaraiyum taNDuzhAi kOmAnaiengaNaindu kANDum ini * ",
            83: "iniyavan mAyan ena uraipparEluminiyavan kANbariyanElum iniyavan * kaLLattAl maN koNDu viNkaDanda paingazhalAnuLLattinuLLE uLan * ",
            84: "uLanAya nAnmaraiyin uTporuLai uLLattuuLanAha tErnduNarvarElum uLanAya * vaNDAmarai neDungaN mAyavanai yAvarEkaNDArugappar kavi * ",
            85: "kaviyinAr kaipunaindu kaNNAr kazhalpOiseviyinAr kELviyarAi sErndAr puviyinAr * pERRiyuraikka poliyumE pinnaikkAiERRuyirai aTTAn ezhil * ",
            86: "ezhil koNDa minnu koDiyeDuttu vEhatozhil koNDu tAn muzhangi tOnrum ezhil koNDa * neermEha manna neDumAl nirampOlakArvAnam kATTum kalandu * ",
            87: "landu maNiyimaikkum kaNNA ninmEnimalarndu marahadamE kATTum nalandihazhum * kondinvAi vaNDaraiyum taNDuzhAi kOmAnaiandivAn kATTum adu * ",
            88: "adunanru iduteedenru aiyappaDAdEmaduninra taNDuzhAi mArvan poduninra * ponnangazhalE tozhumin muzhuvinaigaLmunnangazhalum muDindu * ",
            89: "muDinda pozhudil kuravANar EnampaDinduzhusAl paindinaihaL vitta taDindezhunda * vEingazhaipOi viNtirakkum vEngaDamE mElorunALteenguzhalvAi vaittAn silambu * ",
            90: "silambum serikazhalum senrisaippa viNNAralambiya sEvaDipOi aNDam pulambiyatOL * eNDisaiyum soozha iDampOdAden kolOvaNDuzhAi mAlaLanda maN * ",
            91: "maNNuNDum pEichchi mulaiyuNDum ARRAdAiveNNei vizhunga veguNDu Aichchi kaNNikayiRRinAl kaTTa tAn kaTTuNDirundAnvayiRRinODARRA magan * ",
            92: "magan oruvarkku allAda mAmEni mAyanmaganAm avan mahan tan kAdal mahanai * sirai seida vANan tOL seRRAn kazhalEnirai seidu en nenjE ninai * ",
            93: "ninaittulagilAr teLivAr neeNDa tirumAlanaittulahum uLLoDukki AlmEl kanaittulavu * veLLattOr piLLaiyAi meLLa tuyinrAnaiuLLattEvai nenjE uittu * ",
            94: "uittuNar vennu oLikoL viLakkERRivaittavanai nADi valaippaDuttEn mettenavE * ninrAnirundAn kiDandAnen nenjattuponrAmai mAyan pugundu * ",
            95: "pugundilangum andi pozhudattu ariyAiihazhnda iraNiyanadAham suhirndengum * sinda piLanda tirumAl tiruvaDiyEvanditten nenjamE vAzhttu * ",
            96: "vAzhttiya vAyarAi vAnOr maNimahuDamtAzhtti vaNanga tazhumbAmE kEzhtta * aDittAmarai malarmEl mangai maNALanaDi tAmaraiyAm alar * ",
            97: "alareDutta andiyAn angezhilAyamalareDutta mAmEni mAyan alareDutta * vaNNattAn mAmalarAn vArsaDaiyAnenRu ivargaTkueNNattAnAmO imai * ",
            99: "toTTa paDai eTTum tOlAda venriyAnaTTa buyakarattAn nAnru kuTTattu * kOLmudalai tunja kuritterinda chakkarattAntALmudalE nangaTku sArvu * ",
            100: "sArvu namakkenrum chakkarattAn taNDuzhAitArvAzh varaimArban tAn muyangum kArArnda * vAnamarum min imaikkum vaNDAmarai neDungaNtEnamarum poo mEl tiru * ",
        },
    };

    // Non-destructive runtime merging engine
    for (const key in text_bundle_en) {
        window.MARKER_DATABASE[key] = window.MARKER_DATABASE[key] || [];
        for (const p in text_bundle_en[key]) {
            const idx = parseInt(p) - 1;
            window.MARKER_DATABASE[key][idx] = window.MARKER_DATABASE[key][idx] || { p: parseInt(p) };
            window.MARKER_DATABASE[key][idx]['text'] = window.MARKER_DATABASE[key][idx]['text'] || {};
            window.MARKER_DATABASE[key][idx]['text']['en'] = text_bundle_en[key][p];
        }
    }
};
