window.MARKER_DATABASE = window.MARKER_DATABASE || {};
// Global function to trigger the merge on-demand
window.mergeLanguageTexts = function () {
    const text_bundle_en = {

        'TCV.0.steps': {
            1: "tharuchchandhap pozhil thazhuvu thAraNiyin thuyar thIra * thiruchchandha viruththamsey thirumazhisaip paran varumUr * karuchchandhum kAragilum kamazh kOngum maNanARum * thiruchchandhaththudan maruvu thirumazhisai vaLam padhiyE",
            2: "ulagum mazhisaiyum uLLuNarndhu * thammil pulavar pugazhkkOlAl thUkka * ulagu thannai vaiththeduththa pakkaththum * mAnIr mazhisaiyE vaiththeduththa pakkam validhu.",
        },

        'TCV.1.steps': {
            1: "pUnilAya aindhumAyp * punaRkaN ninRa nAngumAy * theenilAya mUnRumAych * chiRandha kAliraNdumAy * meenilAyadhu onRumAgi * vERuvERu thanmaiyAy * neenilAya vaNNam ninnai * yAr ninaikka vallarE?",
            2: "ARum ARum ARumAy * Or aindhum aindhum aindhumAy * ERu sIr iraNdu mUnRum * EzhumARum ettumAy * vERu vERu gyAnamAgi * meyyinOdu poyyumAy * URodOsaiyAya aindhum * Aya Aya mAyanE!",
            3: "aindhum aindhum aindhumAgi * allavaRRuL AyumAy * aindhu mUnRum onRum Agi * ninRa Adhi dEvanE * aindhum aindhum aindhum Agi * andharaththu aNaindhu ninRu * aindhum aindhum Aya ninnai * yAvar kANa vallarE?",
            4: "mUnRu muppathARinOdu * Or aindhum aindhum aindhumAy * mUnRu mUrththiyAgi mUnRu * mUnRu mUnRu * mUnRumAy * thOnRu sOdhi mUnRumAyth * thuLakkamil viLakkamAy * EnRu en AviyuL pugundhathu * en kolO? em IsanE!",
            5: "ninRiyangum onRalA * urukkaL thORum AviyAy * onRi uL kalandhu ninRa * ninna thanmai innadhenRu * enRum yArkkum eNNiRandha * AdhiyAy! nin undhi vAy * anRu nAnmugaR payandha * Adhi dhEvan allaiyE?",
            6: "nAgam Endhu mEru veRpai * nAgamEndhu maNNinai * nAgam Endhu mAgamAgam * mAgamEndhu vArpunal * mAgam Endhu mangul thI Or * vAyuvaindhamaindhu kAththu Egam Endhi ninRa nIrmai * nin kaNE iyanRadhE",
            7: "onRiraNdu mUrththiyAy * uRakkamOdu uNarchchiyAy * onRiraNdu kAlamAgi * vElai gyAlam AyinAy * onRiraNdu thIyumAgi * AyanAya mAyanE! * onRiraNdu kaNNinAnum * unnai Eththa vallanE?",
            8: "AdhiyAna vAnavarkkum * aNdamAyavappuRaththu * AdhiyAna vAnavarkkum AdhiyAna Adhi nI * AdhiyAna vAna vANar * andha kAlam nI uraiththi * AdhiyAna kAla ninnai * yAvar kANa vallarE?",
            9: "thAdhulAvu konRai mAlai * thunnu senjadaich chivan * nIdhiyAl vaNangu pAdha! * ninmalA ! nilAya sIr * vEdha vANar gIdha vELvi * nIdhiyAna kELviyAr * nIdhiyAl vaNanguginRa * nIrmai nin kaN ninRadhE",
            10: "thannuLE thiraiththezhum * tharangaveN thadangadal * thannuLE thiraiththezhundhu * adanguginRa thanmai pOl * ninnuLE piRandhu iRandhu * niRpavum thiribavum * ninnuLE adanguginRa * nIrmai nin kaN ninRadhE",
            11: "sollinAl thodarchchi nI * solappadum poruLum nI * sollinAl solappadAdhu * thOnRuginRa sOdhi nI * sollinAl padaikka * nI padaikka vandhu thOnRinAr * sollinAl surunga * nin guNangaL solla vallarE?",
            12: "ulagu thannai nI padaiththi * uLLodukki vaiththi * mINdu ulagu thannuLE piRaththi * Oridaththai allaiyAl * ulagu ninnodu onRi niRka * vERu niRRiyAdhalAl * ulagil ninnai uLLa sUzhal * yAvar uLLa vallarE ?",
            13: "innai enRu sollal Avadhu * illaiyAdhum ittidai * pinnai kELvan enbar * un piNakkuNarndha peRRiyOr * pinnaiyAya kOlamOdu * pErum Urum Adhiyum * ninnai yAr ninaikka vallar? * nIrmaiyAl ninaikkilE",
            14: "thUymai yOgamAyinAy * thuzhAy alangal mAlaiyAy * AmaiyAgi Azhkadal thuyinRa * Adhi dhEva! * nin nAmadhEyam innadhenna * vallamallavAgilum * sAma vEdha gIdhanAya * chakrapANi allaiyE?",
            15: "angam ARum vEdham nAngum * Agi ninRu avaRRuLE * thanguginRa thanmaiyAy! * thadangadal paNaththalai * sengaN nAgaNaik kidandha * selvamalgu sIrinAy! * sanga vaNNam anna mEni * sArngapANi allaiyE?",
            16: "thalaik kaNaththugaL kuzhambu * sAdhi sOdhi thORRAmAy * nilaik kaNangaL kANa vandhu * niRRiyElum nIdirum * kalaik kaNangaL soR poruL * karuththinAl ninaikkoNA * malaik kaNangaL pOluNarththum * mAtchi nindhan mAtchiyE",
            17: "Ega mUrththi mUnRu mUrththi * nAlu mUrththi nanmai sEr * bOga mUrththi puNNiyaththin mUrththi * eNNil mUrththiyAy * nAga mUrththi sayanamAy * nalangadal kidandhu * mElAga mUrththiyAya vaNNam * enkol? Adhi dhEvanE!",
            18: "vidaththa vAy orAyiram * irAyiram kaN vendhazhalvidaththu vILvilAtha bOgam * mikka sOdhi thokka sIr * thoduththu mEl vidhAnamAya * pauva nIr arAvaNai * paduththa pAyal paLLi koLvadhu * en kol? vElai vaNNAnE!",
            19: "puLLAdhAgi vEdham nAngum * OdhinAy adhanRiyum * puLLin vAy piLandhu * putkodip pidiththa pinnarum * puLLai UrdhiyAthalAl * adhen kol? minkoL nEmiyAy! * puLLin meyp pagaik kadal kidaththal * kAdhaliththathE",
            20: "kUsamonRum inRi * mAsuNam paduththu vElai nIr * pEsa ninRa dhEvar vandhu * pAda mun kidandhadhum * pAsam ninRa nIril vAzhum * AmaiyAna kEsavA! * Esa anRu nI kidandhavARu * kURu thERavE",
            21: "* aranganE! tharanga nIr * kalanga anRu kunRu sUzh marangaL thEya mAnilam kulunga * mAsuNam sulAy * nerunga nI kadaindha pOdhu * ninRa sUrar en seydhAr? * kurangaiyALugandha endhai! * kURu thERa vERidhE",
            22: "paNdum inRum mElumAy Or * bAlanAgi gyAlamEzhum * uNdu maNdi Alilaith thuyinRa * Adhi dhEvanE ! * vaNdu kiNdu thaN thuzhAy * alangalAy kalandha sIr * puNdarIga pAvai sErum mArba ! * bUmi nAdhanE",
            23: "vAlniRaththor sIyamAy * vaLaindha vAL eyiRRavan * Un niRaththu ugirththalam * azhuththinAy! ulAya sIr * nAl niRaththa vEdha nAvar * nalla yOginAl vaNangu * pAl niRak kadal kidandha * paRpanAbhan allaiyE?",
            24: "gangai nIr payandha pAdha * pangayaththu em aNNalE * angai Azhi sangu thaNdu * villum vALum EndhinAy * singamAya dhEva dhEva! * thEnulAvu menmalar * mangai manni vAzhu mArba! * Azhi mEni mAyanE!",
            25: "varaththinil siraththai mikka * vAL eyiRRu maRRavan * uraththinil karaththai vaiththu * ugirththalaththai UnRinAy * iraththi nI idhenna poy? * irandha maN vayiRRuLEkaraththi * un karuththai yAvar kANa vallar * kaNNanE",
            26: "ANinOdu peNNumAgi * allavOdu nallavAy * UNodu Osai URumAgi * onRalAdha mAyaiyAy * pUNi pENum AyanAgip * poyyinOdu meyyumAy * kANi pENum mANiyAyk * karandhu senRa kaLvanE!",
            27: "viN kadandha sOdhiyAy * viLangu gyAna mUrththiyAy * paN kadandha thEsamEvu * pAva nAsa nAdhanE ! * eN kadandha yOginOdu * irandhu senRu mANiyAy * maN kadandha vaNNam ninnai * yAr madhikka vallarE?",
            28: "padaiththa pAr idandhaLandhu * adhu uNdu umizhndhu pauvanIr * padaiththu adaiththadhil kidandhu * mun kadaindha peRRiyOy! * midaiththa mAli mAlimAn * vilangu kAlanUr puga * padaikkalam viduththa * palpadaith thadakkai mAyanE!",
            29: "paraththilum paraththaiyAdhi * pauva nIr aNaik kidandhu * uraththilum oruththi thannai * vaiththugandhu adhanRiyum * naraththilum piRaththi * nAdha gyAna mUrththi AyinAy! * oruththarum ninAdhu thanmai * innadhenna vallarE?",
            30: "vAnagamum maNNagamum * veRpum EzhkadalgaLum * pOnagam seydhu Alilaith thuyinRa * puNdarIganE! * thEnagam seydhaNNaRum * malarth thuzhAy nan mAlaiyAy!kUnagam pugath theRiththa * koRRa villi allaiyE? *",
            31: "kAla nEmi kAlanE * kaNakkilAdha kIrththiyAy! * gyAlam Ezhum uNdu * paNdu Or bAlanAya paNbanE! * vElai vEva vil vaLaiththa * vel sinaththa vIra! * nin pAlarAya paththar siththam * muththi seyyum mUrththiyE!",
            32: "kurakkinap padai kodu * kurai kadalin mIdhu pOy * arakkar angaranga * venjaram thurandha vAdhi nI * irakka maN koduththavaRkku * irakkam onRum inRiyE * parakka vaiththaLandhu koNda * paRba pAdhan allaiyE?",
            33: "minniRaththu eyiRRarakkan vIzha * venjaram thurandhu * pinnavaRku aruL purindhu * arasaLiththa peRRiyOy! * nanniRaththorin sol Ezhai * pinnai kELva! mannu sIr * ponniRaththa vaNNanAya * puNdarIgan allaiyE?",
            34: "Adhi Adhi Adhi nI * Or aNdam Adhi AdhalAl * sOdhiyAdha sOdhi nI * adhuNmaiyil viLanginAy! * vEdhamAgi vELviyAgi * viNNinOdu maNNumAy * AdhiyAgi AyanAya * mAyam enna mAyamE?",
            35: "ambulAvu mInumAgi * AmaiyAgi AzhiyAr * thambirAnumAgi mikkadhu * anbu mikku adhanRiyum * kombarAvu nuNmarungul * Ayar mAdhar piLLaiyAy * empirAnum Aya vaNNam * en kolO? em IsanE!",
            36: "Adagaththa pUNmulai * asOdhai Aychchi piLLaiyAy * sAduthaiththOr puLLadhAvi * kaLLadhAya pEy magaL * vIda vaiththa veyya kongai * aiya pAlamudhu seydhu * Adagakkai mAdhar vAy * amudham uNdadhen kolO?",
            37: "kAyththanIL viLangani udhirththu * edhirndha pUngurundhamsAyththu * mA piLandha kaiththalaththa * kaNNan enbarAl * Aychchi pAlai uNdu maNNai uNdu * veNNey uNdu * pinpEychchi pAlai uNdu * paNdor EnamAya vAmanA!",
            38: "kadam kalandha van kari * marupposiththu Or poygai vAy * vidam kalandha pAmbin mEl * nadam payinRa nAdhanE! * kudam kalandha kUththanAya * koNdal vaNNa ! thaNthuzhAy * vadam kalandha mAlai mArba! * kAla nEmi kAlanE!",
            39: "veRpeduththu vElai nIr * kalakkinAy adhanRiyum * veRpeduththu vElai nIr * varambu katti vElai sUzh * veRpeduththa inji sUzh * ilangai kattazhiththa nI * veRpeduththu mAri kAththa * mEgavaNNan allaiyE?",
            40: "Anai kAththu Or Anai konRu * adhanRi Ayar piLLaiyAy * Anai mEyththi AneyuNdi * anRu kunRam onRinAl * Anai kAththu maiyarikkaN * mAdharAr thiRaththu * munAnai anRu senRadarththa * mAyam enna mAyamE?",
            41: "AyanAgi Ayar mangai * vEya thOL virumbinAy * Aya! ninnai yAvar vallar? * ambaraththodu imbarAy * mAya! mAya mAyai kol? * adhanRi nI vaguththalum * mAya mAyam AkkinAy * un mAya muRRum mAyamE",
            42: "vERisaindha sekkar mEni * nIRaNindha punsadai * kIRuthingaL vaiththavan * kai vaiththavan kabAlmisai * URu senguruthiyAl * niRaiththa kAraNam thanai * ERu senRadarththa Isa! * pEsu kUsaminRiyE",
            43: "venjinaththa vEzha * veN marupposiththu uruththamA * kanjanaik kadindhu * maNNaLandhu koNda kAlanE! * vanjanaththu vandha pEychchi * Avi pAluL vAnginAy * anjanaththa vaNNanAya * Adhi dhEvan allaiyE ?",
            44: "pAlinIrmai semponIrmai * pAsiyin pasum puRam * pOlum nIrmai poRpudaith thadaththu * vaNdu viNdulAm * neela nIrmai enRivai * niRaindha kAlam nAngumAy * mAlin nIrmai vaiyagam * maRaiththadhu enna nIrmaiyE ?",
            45: "maNNuLAy kol? viNNuLAy kol ? * maNNuLE mayangi ninRu * eNNum eNNagappadAy kol ? * enna mAyai ? nin thamar * kaNNuLAy kol ? sEyai kol ? * anandhan mEl kidandha empuNNiyA! * punandhuzhAy * alangalam punidhanE!",
            46: "thOdu peRRa thaN thuzhAy * alangalAdu senniyAy * kOdu paRRi Azhi Endhi * anjiRaip puL UrdhiyAl * nAdu peRRa nanmai * naNNamillaiyEnum nAyinEn * vIdu peRRu iRappodum * piRappaRukkumA solE",
            47: "kArodoththa mEni nangaL kaNNa! * viNNin nAdhanE ! * nIridaththarAvaNaik * kidaththi enbar, anRiyum * Oridaththaiyallai ellai * illai enbar AdhalAl * sErvidaththai nAyinEn * therindhiRainjumA solE",
            48: "kunRil ninRu vAn irundhu * nIL kadal kidandhu * maN onRu senRadhonRai uNdu * adhonRidandhu panRiyAy * nanRu senRa nAL avaRRuL * nalluyir padaiththu avarkku * anRu thEvamaiththaLiththa * Adhi dhEvan allaiyE?",
            49: "* koNdai koNda kOdhai mIdhu * thEnulAvu kUni kUn * uNdai koNdu arangavOtti * uL magizhndha nAdhan Ur * naNdai uNdu nArai pEra * vALai pAya nIlamE * aNdai koNdu keNdai mEyum * andhaNIr arangamE",
            50: "veN thiraik karungadal * sivandhu vEva munnor nAL * thiN thiRal silaik kai vALi * vitta vIrar sErum Ur * eN thisaik kaNangaLum * iRainjiyAdu thIrththa nIr * vaNdu iraiththa sOlai vEli * mannu sIr arangamE",
            51: "sarangaLaith thurandhu * vil vaLaiththu ilangai mannavan * sirangaL paththaRuththu udhirththa * selvar mannu ponnidam * parandhu ponnirandhu nundhi * vandhalaikkum vAr punal * arangam enbar nAnmugaththu * ayan paNindha kOyilE",
            52: "poRRaiyuRRa muRRal yAnai * pOr ethirndhu vandhadhai * paRRi uRRu maRRadhan * marupposiththa pAgan Ur * siRReyiRRu muRRal mUngil * mUnRu thaNdar onRinar * aRRa paRRar suRRi vAzhum * andhaNIr arangamE",
            53: "mOdiyOdu ilachchaiyAya * sAbam eydhi mukkaNAn * kUdu sEnai makkaLOdu * koNdu maNdi venjamaththu Oda * vANan Ayiram * karam kazhiththa AdhimAl * pIdu kOyil kUdu nIr * arangam enRa pEradhE",
            54: "ilaith thalaich charam thurandhu * ilangai kattazhiththavan * malaith thalaip piRandhizhindhu * vandhu nundhu sandhanam * kulaith thalaiththu iRuththeRindha * kungumak kuzhambinOdu * alaiththozugu kAviri * arangam mEya aNNalE!",
            55: "mannu mAmalark kizhaththi * vaiya mangai maindhanAy * pinnum Ayar pinnai thOL * maNam puNarndhadhanRiyum * unna pAdham enna sindhai * manna vaiththu nalginAy * ponni sUzh arangamEya * puNdarIgan allaiyE?",
            56: "ilangai mannan aindhodaindhu * paindhalai nilaththuga * kalanga anRu senRu konRu * venRi koNda vIranE! * vilangu nUlar vEdha nAvar * nIdhiyAna kELviyAr * valangoLak kudandhaiyuL * kidandha mAlum allaiyE?",
            57: "sangu thangu mun kai nangai * kongai thangal uRRavan * angam manga anRu senRu * adarththeRindha AzhiyAn * kongu thanguvAr kuzhal * madandhaimAr kudaindha nIr * pongu thaN kudandhaiyuL * kidandha puNdarIganE",
            58: "maram keda nadandhadarththu * maththa yAnai maththagaththu * uram kedap pudaiththu * Or kombosiththu ugandha uththamA! * thurangam vAy piLandhu * maNNaLandha pAdha! * vEdhiyarvaram koLak kudandhaiyuL * kidandha mAlum allaiyE",
            59: "sAli vEli thaNvayal * thadangidangu pUmpozhil * kOlamAda nIdu * thaNkudandhai mEya kOvalA! * kAla nEmi vakkaran * karan muran siram avai * kAlanOdu kUda * vil kuniththa viRkai vIranE!",
            60: "* sezhungozhum perum pani pozhindhida * uyarndha vEyvizundhularndhu ezhundhu * viN pudaikkum vEngadaththuL ninRu * ezhundhirundhu thEn porundhu * pUmpozhil thazhaik kozhum * sezhunthadam kudandhaiyuL * kidandha mAlum allaiyE? `",
            61: "* nadandha kAlgaL nondhavO? * nadunga gyAlam EnamAy * idandha mey kulungavO? * vilangu mAlvaraichchuram * kadandha kAl parandha * kAvirik karaik kudandhaiyuL * kidandhavARu ezhundhirundhu * pEsu vAzhi kEsanE!",
            62: "* karaNda mAdu poygaiyuL * karumbanaip perum pazham * puraNdu vIzha vALai pAy * kuRungudi nedundhagAy! * thiraNda thOL iraNiyan * sinangoL Agam onRaiyum * iraNdu kURu seydhugandha * singam enbadhu unnaiyE",
            63: "nanRirundhu yOga nIdhi * naNNuvArgaL sindhaiyuL * senRirundhu thIvinaigaL * thIrththa dhEva dhEvanE! * kunRirundha mAda nIdu * pAdagaththum Uragaththum * ninRirundhu vehkaNaik kidandhadhu * enna nIrmaiyE?",
            64: "ninRadhu endhai Uragaththu * irundhadhu endhai pAdagaththu * anRu vehkaNaik kidandhadhu * ennilAdha munnelAm * anRu nAn piRandhilEn * piRandha pin maRandhilEn * ninRadhum irundhadhum * kidandhadhum en nenjuLE",
            65: "niRpadhum Or veRpagaththu * iruppum viN kidappadhum * naRperundhiraik kadaluL * nAnilAdha munnelAm * aRputhan anandha sayanan * Adhi bUdhan mAdhavan * niRpadhum iruppadhum * kidappadhum en nenjuLE",
            66: "inRu sAdhal ninRu sAdhal * anRiyArum vaiyagaththu * onRi ninRu vAzhdhalinmai kaNdum * nIsar en kolO ? * anRu pAraLandha pAdha * pOdhaiyonRi vAnin mEl * senRu senRu dhEvarAy * irukkilAdha vaNNamE",
            67: "saNda maNdalaththinUdu * senRu vIdu peRRu mEl * kaNdu vIdilAdha kAdhal * inbam nALum eydhuvIr * puNdarIga pAdha puNya kIrththi * num sevi maduththuuNdu * num uRu vinaith * thuyaruL nIngi uymminO",
            68: "muththiRaththu vANiyaththu * iraNdil onRum nIsargaL * maththarAy mayanguginRadhu * ittadhil iRandhu pOndhu * eththiRaththum uyvadhu Or * upAyamillai uykuRil * thoththuRuththa thaN thuzhAy * nanmAlai vAzhththi vAzhminO",
            69: "kANilum uruppolAr * sevikkinAdha kIrththiyAr * pENilum varam thara * midukkilAdha thEvarai * ANam enRadaindhu vAzhum * AdhargAL! em Adhi pAl * pENi num piRappenum * piNakku aRukka kiRRirE",
            70: "kundhamOdu sUlam vElgaL * thOmarangaL thaNdu vAL * pandhamAna dhEvargaL * parandhu vAnagam uRa * vandha vANan IraingyURu * thOLgaLaith thuNiththa nAL * andha vandha Akulam * amararE aRivarE",
            71: "vaNdulAvu kOdhai mAdhar * kAraNaththinAl veguNdu * iNda vANan IraingyURu * thOLgaLaith thuNiththa nAL * muNdan nIRan makkaL veppu * mOdi angi OdidakkaNdu * nANi vANanukku iranginAn * em mAyanE",
            72: "pOdhil mangai bUdhalak kizhaththi * dhEvi anRiyum * pOdhu thangu nAnmugan * magan avan magan solil * mAdhu thangu kURan * ERadhu Urdhi enRu vEdha nUl * OdhuginRadhu uNmai alladhillai * maRRu uraikkilE",
            73: "maram podhach charam thurandhu * vAli vIzha munnOr nAL * uram podhach charam thurandha * umbarALi empirAn * varam kuRippil vaiththavarkku * alAdhu vAnam ALilum * nirambu nIdu bOgam * eththiRaththum yArkkum illaiyE",
            74: "aRindhu aRindhu vAmanan * adiyiNai vaNanginAl * seRindhu ezhundha gyAnamOdu * selvamum siRandhidum * maRindhu ezhundha theN thiraiyuL * mannu mAlai vAzhththinAl * paRindhu ezhundhu thIvinaigaL * paRRaRudhal pAnmaiyE",
            75: "onRi ninRu naRRavam seydhu * Uzhi Uzhi thORelAm * ninRu ninRu avan guNangaL * uLLi uLLam thUyarAy * senRu senRu dhEva dhEvar * umbar umbar umbarAy * anRi engaL sengaN mAlai * yAvar kANa vallarE?",
            76: "punpula vazhi adaiththu * arakkilachchinai seydhu * nanpula vazhi thiRandhu * gyAna naR sudar koLIi * enbileLgi nenjurugi * uL kanindhu ezhundhadhOr * anbilanRi AzhiyAnai * yAvar kANa vallarE?",
            77: "ettum ettum ettumAy * OrEzhum Ezhum EzhumAy * ettu mUnRum onRumAgi * ninRa Adhi dhEvanai * ettinAya pEdhamOdu * iRainji ninRu avan peyar * ettezuththum OdhuvArgaL * vallar vAnam ALavE",
            78: "sOrvilAdha kAdhalAl * thodakkaRA manaththarAy * nIr arAvaNaik kidandha * ninmalan nalangazhal * ArvamOdu iRainji ninRu * avan peyar ettezhuththum * vAramAga OdhuvArgaL * vallar vAnam ALavE",
            79: "paththinOdu paththumAy * Or EzhinOdu Or onbathAy * paththinAl thisaik kaN ninRa * nAdu peRRa nanmaiyAy * paththinAya thORRamOdu * orARRal mikka Adhi pAl * paththarAm avarkku alAdhu * muththi muRRalAgumE?",
            80: "vAsiyAgi nEsaminRi * vandheirndha thEnugan * nAsamAgi nALulappa * nanmai sEr pananganikku vIsi * mEl nimirndha thOLil * illaiyAkkinAy kazhaRku * AsaiyAm avarkkalAl * amarar Agal AgumE?",
            81: "kadaindhu pARkadal kidandhu * kAla nEmiyaik kadindhu * udaindha vAli than thanakku * udhava vandha irAmanAy * midaindha Ezh marangaLum * adanga eydhu vEngadam * adaindha mAla pAdhamE * adaindhu nALum uymminO",
            82: "eththiRaththum oththu ninRu * uyarndhuyarndha peRRiyOy * muththiRaththu mUri nIr * arAvaNaith thuyinRa * nin paththuRuththa sindhaiyOdu * ninRu pAsam vittavarkku * eththiRaththum inbam * ingum angum engum AgumE",
            83: "mattulAvu thaNthuzhAy * alangalAy pulan kazhal * vittu vILvilAdha bOgam * viNNil naNNi ERinum * ettinOdu iraNdenum * kayiRRinAl manandhanaikkatti * vIdilAdhu vaiththa kAdhal * inbam AgumE",
            84: "pin piRakka vaiththanan kol ? * anRi ninRu than kazhaRku * anbuRaikka vaiththa nAL * aRindhanan kol AzhiyAn * than thiRaththu Or anbilA * aRivilAdha nAyinEn * en thiRaththil en kol? * empirAn kuRippil vaiththadhE",
            85: "nachcharAvaNaik kidandha * nAdha! pAdha pOdhinil * vaiththa sindhai vAnguviththu * nInguvikka nI inam * meyththan vallai AdhalAl * aRindhanan nin mAyamE * uyththu nin mayakkinil * mayakkal ennai mAyanE!",
            86: "sAdu sAdu pAdhanE! * salam kalandha poygai vAy * AdarAvin vanpidar * nadam payinRa nAdhanE! * kOdu nIdu kaiya seyya * pAdham nALum uLLinAl * vIdanAga mey seyAdha * vaNNam en kol? kaNNanE!",
            87: "neRRi peRRa kaNNan * viNNin nAdhanOdu pOdhin mEl * naRRavaththu nAdhanOdu * maRRumuLLa vAnavar * kaRRa peRRiyAl vaNangu * pAdha! nAdha! vEdha! * ninpaRRalAl Or paRRu * maRRadhu uRRilEn uraikkilE",
            88: "veLLai vElai veRpu nAtti * veLLeyiRRu arAvaLAy * aLLalAk kadaindha anRu * aruvaraikku Or AmaiyAy * uLLa nOygaL thIr marundhu * vAnavarkku aLiththa * emvaLLalArai anRi * maRROr dheyvam nAn madhippanE?",
            89: "pAr miguththa bAram mun * ozhichchuvAn aruchchunan * thEr miguththu mAyamAkki * ninRu konRu venRi sEr * mAradharkku vAn koduththu * vaiyam aivar pAladhAm * sIr miguththa ninnalAl Or * dheyvam nAn madhippanE?",
            90: "kulangaLAya IriraNdil * onRilum piRandhilEn * nalangaLAya naRkalaigaL * nAlilum navinRilEn * pulangaL aindhum venRilEn * poRiyilEn punidha! * ninilangu pAdham anRi * maRROr paRRilEn em IsanE!",
            91: "paNNulAvu menmozhip * padaith thadangaNAL poruttu * eNNilA arakkarai * neruppinAl nerukkinAy * kaNNalAl Or kaNNilEn * kalandha suRRam maRRilEn * eNNilAdha mAya! ninnai * ennuL nIkkal enRumE",
            92: "* vidaik kulangaL Ezhadarththu * venRi vERkaN mAdharAr * kadik kalandha thOL puNarndha * kAli Aya! vElai nIr * padaiththu adaiththu adhil kidandhu * mun kadaindhu nin thanakku * adaikkalam pugundha ennai * anjal enna vENdumE",
            93: "surumbarangu thaN thuzhAy * thudhaindhalarndha pAdhamE * virumbi ninRu iRainjuvERku * irangu aranga vANanE! * karumbirundha kattiyE! * kadal kidandha kaNNanE! * irumbaranga venjaram thurandha * villi rAmanE!",
            94: "Unil mEya Avi nI * uRakkamOdu uNarchchi nI * Anil mEya aindhum nI * avaRRuL ninRa thUymai nI * vAninOdu maNNum nI * vaLangadaR payanum nI * yAnum nI adhanRi * empirAnum nI irAmanE!",
            95: "adakkarum pulangaL aindhadakki * AsaiyAm avai * thodakkaRuththu vandhu * nin thozhiRkaN ninRa ennai nI * vidak karudhi mey seyAdhu * mikkOr Asai Akkilum * kadal kidandha ninnalAl Or * kaNNilEn em aNNalE!",
            96: "varambilAdha mAyai mAya * vaiyam Ezhum meymmaiyE * varambil Uzhi Eththilum * varambilAdha kIrththiyAy! * varambilAdha pal piRappu * aRuththu vandhu nin kazhal * porundhumA thirundha nI * varam sey puNdarIganE!",
            97: "veyya vAzhi sangu thaNdu * villum vALum Endhu sIrk kaiya * seyya pOdhil mAdhu * sErum mArba! nAdhanE! * aiyilAya Akkai nOy * aRuththu vandhu ninnadaindhu * uyvadhOr upAyam nI * enakku nalga vENdumE",
            98: "maRam thuRandhu vanjam mARRi * aimpulangaL Asaiyum thuRandhu * nin kaN AsaiyE * thodarndhu ninRa nAyinEn * piRandhiRandhu pEridarch * chuzhikkaNinRu nIngumA * maRandhidAdhu maRRu enakku * mAya! nalga vENdumE",
            99: "kAtti nAn sey valvinai * payan thanAl manam thanai * nAtti vaiththu nalla valla * seyya eNNinAr ena * kEttadhanRi ennadhAvi * pinnai kELva! ninnodum * pUtti vaiththa ennai * ninnuL nIkkal pUvai vaNNanE!",
            100: "piRappinOdu pEridarch * suzhikkaN ninRum nIngum ahdhu iRappa vaiththa gyAna nIsaraik * karaikkodERRumA * peRaRkariya ninna pAdha * paththiyAna pAsanam * peRaRkariya mAyanE! * enakku nalga vENdumE *",
            101: "irandhu uraippadhuNdu vAzhi * Ema nIr niRaththamA! * varandharum thirukkuRippil * vaiththadhAgil mannu sIr * parandha sindhai onRi ninRu * ninna pAdha pangayam * nirandharam ninaippadhAga * nI ninaikka vENdumE",
            102: "viLvilAdha kAdhalAl * viLangu padha pOdhil vaiththu * uLLuvEnadhu Una nOy * ozhikkumA thezhikku nIr * paLLi mAya! panRiyAya * venRi vIra! kunRinAl * thuLLu nIr varambu seydha * thOnRal! onRu sollidE",
            103: "thirukkalandhu sErum mArba! * dhEva dhEva dhEvanE! irukkalandha vEdha nIdhi * Agi ninRa ninmalA! * karukkalandha kALamEga * mEniyAya nin peyar * urukkalandhu ozhivilAdhu * uraikkumARu urai seyE",
            104: "kadungavandhan vakkaran * karan muran siramavai * idandhu kURu seydha * palpadaith thadakkai mAyanE! * kidandhu irundhu ninRiyangu * pOdhum ninna poRkazhal * thodarndhu viLvilAdhadhOr * thodarchchi nalga vENdumE",
            105: "maNNai uNdu umizhndhu pin * irandhu koNdaLandhu maN * kaNNuL alladhillai enRu * venRa kAlamAyinAy! * paNNai venRa insol mangai * kongai thangu pangayakkaNNa! * ninna vaNNam alladhillai * eNNum vaNNamE",
            106: "kaRuththu ethirndha kAla nEmi * kAlanOdu kUda * anRu aRuththa Azhi sangu thaNdu * villum vALum EndhinAy! * thoRukkalandha Unamahdhu * ozhikka anRu kunRam mun * poRuththa nin pugazhkkalAl Or * nEsamillai nenjamE!",
            107: "kAysinaththa kAsi mannan * vakkaran pavuNdiran * mAsinaththa mAli mAn * sumAlikEsi thEnugan * nAsam uRRu vIzha * nAL kavarndha nin kazhaRkalAl * nEsa pAsam eththiRaththum * vaiththidEn em IsanE!",
            108: "kEdil sIr varaththanAyk * kedum varaththu ayan aran * nAdinOdu nAttamAyiraththan * nAdu naNNinum * vIdadhAna bOgam eydhi * vIRRirundha pOdhilum * kUdum Asai alladhonRu * koLvanO? kuRippilE",
            109: "surukkuvArai inRiyE * surunginAy surungiyum * perukkuvArai inRiyE * perukkameydhu peRRiyOy! * serukkuvArgaL thIkkuNangaL * thIrththa dhEva dhEvan enRu * irukkuvAy munik kaNangaL Eththa * yAnum EththinEn",
            110: "thUyanAyum anRiyum * surumbulAvu thaNthuzhAy * mAya ninnai nAyinEn * vaNangi vAzhththum IdhelAm * nIyum nin kuRippinil * poRuththu nalgu vElai nIr * pAyalOdu paththar siththam * mEya vElai vaNNanE!",
            111: "vaidhu ninnai vallavA * pazhiththavarkkum mARil pOr * seydhu ninna seRRa thIyil * vendhavarkkum vandhunnai * eydhalAgum enbar * AdhalAl em mAya! nAyinEn * seydha kuRRam naRRamAgavE koL * gyAla nAdhanE!",
            112: "vALgaLAgi nALgaL sella * nOymai kunRi mUppeydhi * mALunAL adhu AdhalAl * vaNangi vAzhththu en nenjamE! * ALadhAgum nanmai enRu * nanguNarndhadhu anRiyum * mILvilAdha bOgam * nalga vENdum mAla pAdhamE",
            113: "salangalandha senjadaik * kaRuththa kaNdan veN thalai * pulan kalanga uNda pAdhagaththan * van thuyar keda * alangal mArvil vAsa nIr * koduththavan aduththa sIr * nalangoL mAlai naNNum vaNNam * eNNu vAzhi nenjamE",
            114: "InamAya ettum nIkki * EdhaminRi mIdhu pOy * vAnam ALa vallaiyEl * vaNangi vAzhththu en nenjamE! * gyAnamAgi gyAyiRAgi * gyAlam muRRum Or eyiRRu * EnamAy idandha mUrththi * endhai pAdham eNNiyE",
            115: "* aththanAgi annaiyAgi * ALum empirAnumAy * oththu ovvAdha palpiRappozhiththu * nammai AtkoLvAn * muththanAr mugundhanAr * pugundhu nammuL mEvinAr * eththinAl idarkkadal kidaththi ? * Ezhai nenjamE!",
            116: "mARu seydha vALarakkan * nALulappa anRu ilangai * nIRu seydhu senRu konRu * venRi koNda vIranAr * vERu seydhu thammuL ennai * vaiththidAmaiyAl * naman kURu seydhu koNdiRandha * kuRRam eNNa vallanE?",
            117: "achcham nOyodu allal palpiRappu * Aya mUppivai * vaiththa sindhai vaiththa Akkai * mARRi vAnil ERRuvAn achchudhan anandha kIrththi * Adhi andham illavan * nachchu nAgaNaik kidandha * nAdhan vEdha gItdanE.",
            118: "sollinum thozhiRkaNum * thodakkaRAdha anbinum * allum nanpagalinOdum * Ana mAlai kAlaiyum * valli nANmalark kizhaththi * nAdha pAdha pOdhinai * pulli uLLam viLvilAdhu * pUNdu mINdadhu illaiyE",
            119: "* ponni sUzh aranga mEya * pUvai vaNNa! mAya! kEL * ennadhAvi ennum * valvinaiyin utkozhundhezhundhu * unna pAdhamenna ninRa * oNsudark kozhumalar * manna vandhu pUNdu * vAttaminRi engum ninRadhE",
            120: "* iyakkaRAdha palpiRappil * ennai mARRi inRu vandhu * uyakkoL mEga vaNNan naNNi * ennilAya thannuLE * mayakkinAn than mannu sOdhi * AdhalAl ennAvi thAn * iyakkelAm aRuththu * aRAdha inba vIdu peRRadhE",

        }
    };

    // Non-destructive runtime merging engine
    for (const key in text_bundle_en) {
        window.MARKER_DATABASE[key] = window.MARKER_DATABASE[key] || [];
        for (const p in text_bundle_en[key]) {
            const idx = parseInt(p) - 1;
            window.MARKER_DATABASE[key][idx] = window.MARKER_DATABASE[key][idx] || { p: parseInt(p) };
            window.MARKER_DATABASE[key][idx]['text'] = window.MARKER_DATABASE[key][idx]['text'] || {};
            window.MARKER_DATABASE[key][idx]['text']['en'] = text_bundle_en[key][p];
        }
    }
};