window.MARKER_DATABASE = window.MARKER_DATABASE || {};
// Global function to trigger the merge on-demand
window.mergeLanguageTexts = function () {
    const text_bundle_en = {

        'TPV.0.steps': {
            1: "parAsara baTTar aruLich cheydhadhu : nILA tungga stana giri taTI suptam udbOdhya krushNam * pArArthyam svam shruti shata shirassiddham adhyApayantI * svOchChiShTAyAm sraji nigaLitam yA balAtkrutya bhungkte * gOdA tasyai nama idamidam bhUya EvA-stu bhUya: *",
            2: "uyyakkoNDAr aruLich cheydhadhu : anna vayal pudhuvai ANDAL * aranggaRkup pannu thiruppAvaip palpadhiyam * - innisaiyAl pADik koDuththAL naRpAmAlai * pUmAlai sUDik koDuththALaich sollu *",
            3: "uyyakkoNDAr aruLich cheydhadhu : sUDik koDuththa suDarkkoDiyE! * tholpAvai pADi aruLa valla palvaLaiyAy! * - nADi nI vEngkaDavaRku ennai vidhi enRa immARRam * nAm kaDavA vaNNamE nalgu *",
        },

        'TPV.1.steps': {
            1: "* mArgazhith thinggaL madhi niRaindha nannALAl * nIrADap pOdhuvIr! pOdhuminO nErizhaiyIr! * sIr malgum AyppADich selvach siRumIrgAL! * kUrvEl koDunthozhilan nandhagOpan kumaran *** ErArndha kaNNi yasOdhai iLanjchinggam * kArmEnich sengkaN kadhir madhiyam pOl mugaththAn * nArAyaNanE namakkE paRai tharuvAn * pArOr pugazhap paDindhElOr empAvAy ",
            2: "vaiyaththu vAzhvIrgAL! nAmum nam pAvaikkuch * seyyum kirisaigaL kELIrO * pARkaDaluL paiyath thuyinRa paraman aDi pADi * ney uNNOm pAl uNNOm nATkAlE nIrADi *** maiyiTTu ezhudhOm malariTTu nAm muDiyOm * seyyAdhana seyyOm thIkkuRaLaich senRu OdhOm * aiyamum pichchaiyum Anthanaiyum kai kATTi * uyyum ARu eNNi ugandhElOr empAvAy ",
            3: "* Onggi ulagaLandha uththaman pEr pADi * nAnggaL nam pAvaikkuch sARRi nIrADinAl * thInggu inRi nADellAm thinggaL mummAri peydhu * Onggu peRum sennelUDu kayal ugaLa *** pUngkuvaLaip pOdhil poRi vaNDu kaN paDuppa * thEnggAdhE pukkirundhu sIrththa mulai paRRi vAngga * kuDam niRaikkum vaLLal perum pasukkaL * nInggAdha selvam niRaindhElOr empAvAy ",
            4: "Azhi mazhaik kaNNA! onRu nI kai karavEl * AzhiyuL pukku mugandhu koDu ArththERi * Uzhi mudhalvan uruvam pOl mey kaRuththu * pAzhi anthOLuDaip paRpanAban kaiyil *** Azhi pOl minni valampuri pOl ninRu adhirndhu * thAzhAdhE sArnggam udhaiththa sara mazhai pOl * vAzha ulaginil peydhiDAy * nAnggaLum mArgazhi nIrADa magizhndhElOr empAvAy ",
            5: "mAyanai mannu vaDamadhurai maindhanai * thUya peru nIr yamunaith thuRaivanai * Ayar kulaththinil thOnRum aNiviLakkai * thAyaik kuDal viLakkam seydha dhAmOdharanai *** thUyOmAy vandhu nAm thUmalar thUvith thozhudhu * vAyinAl pADi manaththinAl sindhikka * pOya pizhaiyum pugutharuvAn ninRanavum * thIyinil thUsAgum seppElOr empAvAy ",
            6: "puLLum silambina kAN puL araiyan kOyil * veLLai viLi sanggin pEraravam kETTilaiyO? * piLLAy! ezhundhirAy pEy mulai nanjchuNDu * kaLLach sagaDam kalakkazhiyak kAl Ochchi *** veLLaththu aravil thuyil amarndha viththinai * uLLaththuk koNDu munivargaLum yOgigaLum * meLLa ezhundhu ari enRa pEraravam * uLLam pugundhu kuLirndhElOr empAvAy ",
            7: "kIsu kIsenRu enggum AnaichchAththan * kalandhu pEsina pEchcharavam kETTilaiyO? pEyppeNNE! * kAsum piRappum kalakalappak kai pErththu * vAsa naRungkuzhal Aychchiyar *** maththinAl Osai paDuththath thayiraravam kETTilaiyO? * nAyagap peNpiLLAy! nArAyaNan mUrththi * kEsavanaip pADavum nI kETTE kiDaththiyO? * thEsam uDaiyAy! thiRavElOr empAvAy ",
            8: "kIzhvAnam veLLenRu erumai siRuvIDu * mEyvAn parandhana kAN mikkuLLa piLLaigaLum * pOvAn pOginRAraip pOgAmal kAththu * unnaik kUvuvAn vandhu ninROm *** kOdhukalam uDaiya pAvAy! ezhundhirAy pADip paRai koNDu * mA vAy piLandhAnai mallarai mATTiya * dhEvAdhi dhEvanaich senRu nAm sEviththAl * AvA enRu ArAyndhu aruLElOr empAvAy ",
            9: "thUmaNi mADaththuch suRRum viLakku eriyath * dhUpam kamazhath thuyilaNai mEl kaN vaLarum * mAmAn magaLE! maNik kadhavam thAL thiRavAy * mAmIr! avaLai ezhuppIrO? *** un magaL thAn UmaiyO? anRich seviDO? ananthalO? * Emap perunthuyil mandhirap paTTALO? * mAmAyan mAdhavan vaikunthan enRenRu * nAmam palavum navinRElOr empAvAy ",
            10: "nORRuch suvarkkam pugukinRa ammanAy! * mARRamum thArArO? vAsal thiRavAdhAr * nARRath thuzhAy muDi nArAyaNan * nammAl pORRap paRai tharum puNNiyanAl *** paNDoru nAL kURRaththin vAy vIzhndha kumbakaraNanum * thORRum unakkE perunthuyil thAn thandhAnO * ARRa ananthal uDaiyAy! arungkalamE! * thERRamAy vandhu thiRavElOr empAvAy ",
            11: "kaRRuk kaRavaik kaNanggaL pala kaRandhu * seRRAr thiRal azhiyach senRu seruch seyyum * kuRRam onRu illAdha kOvalar tham poRkoDiyE! * puRRaravalgul punamayilE! pOdharAy! *** suRRaththuth thOzhimAr ellArum vandhu * nin muRRam pugundhu mugil vaNNan pEr pADa * siRRAdhE pEsAdhE selvap peNDATTi! * nI eRRukku uRanggum poruLElOr empAvAy ",
            12: "kanaiththu iLam kaRRerumai kanRukku iranggi * ninaiththu mulai vazhiyE ninRu pAl sOra * nanaiththu illam sERAkkum naRselvan thanggAy! * panith thalai vIzha nin vAsal kaDai paRRi *** sinaththinAl thennilanggaik kOmAnaich seRRa * manaththukku iniyAnaip pADavum nI vAy thiRavAy * inith thAn ezhundhirAy Idhenna pEruRakkam! * anaiththu illaththArum aRindhElOr empAvAy ",
            13: "puLLin vAy kINDAnaip pollA arakkanai * kiLLik kaLaindhAnaik kIrththimai pADip pOy * piLLaigaL ellArum pAvaik kaLam pukkAr * veLLi ezhundhu viyAzham uRanggiRRu *** puLLum silambina kAN pOdharik kaNNinAy! * kuLLak kuLirak kuDaindhu nIrADAdhE * paLLik kiDaththiyO? pAvAy! nI nannALAl * kaLLam thavirndhu kalandhElOr empAvAy ",
            14: "unggaL puzhaikkaDaith thOTTaththu vAviyuL * sengkazhunIr vAy negizhndhu Ambal vAy kUmbina kAN * senggal poDikkUrai veNpal thavaththavar * thanggaL thirukkOyil sanggiDuvAn pOginRAr *** enggaLai munnam ezhuppuvAn vAy pEsum * nanggAy! ezhundhirAy nANAdhAy! nAvuDaiyAy! * sanggoDu chakkaram Endhum thaDakkaiyan * panggayak kaNNAnaip pADElOr empAvAy ",
            15: "ellE! iLangkiLiyE! innam uRanggudhiyO! * sillenRu azhaiyEnmin! nanggaimIr! pOdharginREn * vallai un kaTTuraigaL paNDE un vAy aRidhum * vallIrgaL nInggaLE nAnE thAn AyiDuga *** ollai nI pOdhAy unakkenna vERuDaiyai * ellArum pOndhArO? pOndhAr pOndheNNik koL * vallAnai konRAnai mARRArai mARRazhikka vallAnai * mAyanaip pADElOr empAvAy ",
            16: "* nAyaganAy ninRa nandhagOpanuDaiya kOyil kAppAnE! * koDith thOnRum thOraNa vAsal kAppAnE! * maNik kadhavam thAL thiRavAy * Ayar siRumiyarOmukku *** aRai paRai mAyan maNivaNNan nennalE vAy nErndhAn * thUyOmAy vandhOm thuyil ezhap pADuvAn * vAyAl munnamunnam mARRAdhE ammA! * nI nEsa nilaik kadhavam nIkkElOr empAvAy ",
            17: "ambaramE thaNNIrE sORE aRam seyyum * emperumAn! nandhagOpAlA! ezhundhirAy * kombanArkku ellAm kozhundhE! kulaviLakkE! * emperumATTi yasOdhAy! aRivuRAy *** ambaram UDaRuththu Onggi ulagaLandha * umbar kOmAnE uRanggAdhu ezhundhirAy * sempoRkazhal aDich selvA! baladhEvA! * umbiyum nIyum uRanggElOr empAvAy ",
            18: "* undhu madha kaLiRRan ODAdha thOL valiyan * nandhagOpAlan marumagaLE! nappinnAy! * gandham kamazhum kuzhalI! kaDai thiRavAy * vandhu enggum kOzhi azhaiththana kAN *** mAdhavip pandhal mEl palkAl kuyil inanggaL kUvina kAN * pandhAr virali! un maiththunan pEr pADa * senthAmaraik kaiyAl sIrAr vaLai olippa * vandhu thiRavAy magizhndhElOr empAvAy ",
            19: "kuththu viLakku eriyak kOTTuk kAl kaTTil mEl * meththenRa panjcha sayanaththin mEl ERi * koththalar pUngkuzhal nappinai konggai mEl * vaiththuk kiDandha malar mArbA! vAy thiRavAy *** maiththaDam kaNNinAy! nI un maNALanai * eththanai pOdhum thuyil ezha oTTAy kAN * eththanaiyElum pirivu ARRa killAyAl * thaththuvam anRu thagavElOr empAvAy ",
            20: "muppaththu mUvar amararkku mun senRu * kappam thavirkkum kaliyE! thuyil ezhAy * seppam uDaiyAy! thiRal uDaiyAy! * seRRArkku veppam koDukkum vimalA! thuyil ezhAy *** seppanna menmulaich sevvAych siRu marunggul * nappinnai nanggAy! thiruvE! thuyil ezhAy * ukkamum thaTToLiyum thandhu un maNALanai * ippOdhE emmai nIrATTElOr empAvAy ",
            21: "ERRa kalanggaL edhir ponggi mIdhaLippa * mARRAdhE pAl soriyum vaLLal perum pasukkaL * ARRap paDaiththAn maganE! aRivuRAy * URRam uDaiyAy! periyAy! *** ulaginil thORRamAy ninRa suDarE! thuyil ezhAy * mARRAr unakku valitholaindhu un vAsaR kaN * ARRAdhu vandhu unnaDi paNiyumA pOlE * pORRi yAm vandhOm pugazhndhElOr empAvAy ",
            22: "angkaN mA njAlaththarasar * abimAna panggamAy vandhu nin paLLik kaTTil kIzhE * sanggam iruppAr pOl vandhu thalaippeydhOm * kingkiNi vAych cheydha thAmaraip pUp pOlE *** sengkaN siRuch chiRidhE em mEl vizhiyAvO * thinggaLum Adhiththiyanum ezhundhAR pOl * angkaN iraNDum koNDu enggaL mEl nOkkudhiyEl * enggaL mEl sAbam izhindhElOr empAvAy ",
            23: "* mAri malai muzhainjchil mannik kiDandhu uRanggum * sIriya singgam aRivuRRuth thI vizhiththu * vEri mayir pongga eppADum pErndhu udhaRi * mUri nimirndhu muzhanggip puRappaTTu *** pOdharumA pOlE nI pUvaip pU vaNNA! * un kOyil ninRu ingnganE pOndharuLi * kOppuDaiya sIriya singgAsanaththu irundhu * yAm vandha kAriyam ArAyndhu aruLElOr empAvAy ",
            24: "* anRu ivvulagam aLandhAy! aDi pORRi * senRu angguth thennilanggai seRRAy! thiRal pORRi * ponRach sagaDam udhaiththAy! pugazh pORRi * kanRu kuNilA eRindhAy! kazhal pORRi *** kunRu kuDaiyA eDuththAy! guNam pORRi * venRu pagai keDukkum nin kaiyil vEl pORRi * enRenRun sEvagamE Eththip paRai koLvAn * inRu yAm vandhOm iranggElOr empAvAy ",
            25: "oruththi maganAyp piRandhu * Or iravil oruththi maganAy oLiththu vaLara * tharikkilAn Agith thAn thInggu ninaindha * karuththaip pizhaippiththuk kanjchan vayiRRil *** neruppenna ninRa neDumAlE! * unnai aruththiththu vandhOm paRai tharudhi Agil * thiruth thakka selvamum sEvagamum yAm pADi * varuththamum thIrndhu magizhndhElOr empAvAy ",
            26: "mAlE! maNivaNNA! mArgazhi nIrADuvAn * mElaiyAr seyvanagaL vENDuvana kETTiyEl * njAlaththai ellAm naDungga muralvana * pAlanna vaNNaththu un pAnjchasanniyamE *** pOlvana sangganggaL pOyppADu uDaiyanavE * sAlap perum paRaiyE pallANDu isaippArE * kOla viLakkE koDiyE vidhAnamE * Alin ilaiyAy! aruLElOr empAvAy ",
            27: "* kUDArai vellum sIrk gOvindhA! * undhannaip pADip paRai koNDu yAm peRu sammAnam * nADu pugazhum parisinAl nanRAga * sUDagamE thOLvaLaiyE thODE sevippUvE *** pADagamE enRanaiya palkalanum yAm aNivOm * ADai uDuppOm adhan pinnE pAR sORu * mUDa ney peydhu muzhangkai vazhi vAra * kUDi irundhu kuLirndhElOr empAvAy ",
            28: "* kaRavaigaL pin senRu kAnam sErndhu uNbOm * aRivu onRum illAdha Aykkulaththu * undhannaip piRavi peRundhanai puNNiyam yAm uDaiyOm * kuRai onRum illAdha gOvindhA! *** undhannODu uRavEl namakku inggu ozhikka ozhiyAdhu * aRiyAdha piLLaigaLOm anbinAl * undhannaich siRu pEr azhaiththanavum sIRi aruLAdhE * iRaivA! nI thArAy paRaiyElOr empAvAy ",
            29: "* chiRRam chiRu kAlE vandhu unnaich sEviththu * un poRRAmarai aDiyE pORRum poruL kELAy * peRRam mEyththu uNNum kulaththil piRandhu * nI kuRREval enggaLaik koLLAmal pOgAdhu *** iRRaip paRai koLvAn anRu kAN gOvindhA! * eRRaikkum Ezh Ezh piRavikkum * undhannODu uRROmE AvOm unakkE nAm ATseyvOm * maRRai nam kAmanggaL mARRElOr empAvAy ",
            30: "* vanggak kaDal kaDaindha mAdhavanaik kEsavanaith * thinggaL thirumugaththuch sEyizhaiyAr senRu iRainjchi * anggu appaRai koNDa ARRai * aNi pudhuvaip paingkamalath thaNtheriyal paTTarpirAn kOdhai sonna *** sanggath thamizh mAlai muppadhum thappAmE * inggu ipparisu uraippAr IriraNDu mAl varaith thOL * sengkaN thirumugaththuch selvath thirumAlAl * enggum thiruvaruL peRRu inbuRuvar empAvAy ",
        }
    };

    // Non-destructive runtime merging engine
    for (const key in text_bundle_en) {
        window.MARKER_DATABASE[key] = window.MARKER_DATABASE[key] || [];
        for (const p in text_bundle_en[key]) {
            const idx = parseInt(p) - 1;
            window.MARKER_DATABASE[key][idx] = window.MARKER_DATABASE[key][idx] || { p: parseInt(p) };
            window.MARKER_DATABASE[key][idx]['text'] = window.MARKER_DATABASE[key][idx]['text'] || {};
            window.MARKER_DATABASE[key][idx]['text']['en'] = text_bundle_en[key][p];
        }
    }
};