window.MARKER_DATABASE = window.MARKER_DATABASE || {};
// Global function to trigger the merge on-demand
window.mergeLanguageTexts = function () {
    const text_bundle_en = {

        'TNT.0.steps': {
        },

        'TNT.1.steps': {
            1: "minnuruvAy munnuruvil vEdham nAngAy * viLakkoLiyAy muLaiththezhundha thingaL thAnAy * pinnuruvAy munnuruvil piNi mUppillAp * piRappiliyAy iRappadhaRkE eNNAdhu *** eNNum ponnuruvAy maNiyuruvil bhUtham aindhAy * punaluruvAy analuruvil thigazhum sOdhi * thannuruvAy ennuruvil ninRa endhai * thaLir puraiyum thiruvadi en thalai mElavE. *",
            2: "pAruruvi neererikAl visumbumAgip * palvERu samayamumAyp parandhu ninRa * Eruruvil mUvarumEyenna ninRa * imaiyavar tham thiruvuruvEReNNum pOdhu *** Oruruvam ponnuruvam onRu senthee * onRumA kadaluruvam oththu ninRa * mUvuruvum kaNda pOdhu onRAm sOdhi * mugiluruvam emmadigaL uruvam thAnE *",
            3: "thiruvadivil karunedumAl sEyan enRum * thirEthaikkaN vaLaiyuruvAyth thigazhndhAnenRum * peruvadivil kadal amudham koNda kAlam * perumAnaik karuneela vaNNan thannai *** oruvadivaththOruruvenRu uNaralAgA(dhu) * Uzhi thORuzhi ninREththal allAl * karuvadiviR chenkaNNa vaNNan thannaik * katturaiyE yAroruvar kANkiRpArE *",
            4: "indhirarkkum piramarkkum mudhalvan thannai * iru nilam kAl thee neer viN bUtham aindhAy * senthiRaththa thamizhOsai vada sollAgith * thisai nAngumAyth thingaL nAyirAgi  *** antharaththil dhEvarkkum aRiyalAgA anthaNanai * anthaNar mAttu andhi vaiththa manthiraththai * manthiraththAl maRavAdhenRum * vAzhudhiyEl vAzhalAm mada nenjamE. *",
            5: "oNmidhiyil punaluruvi orukAl niRpa * orukAlum kAmaruseer avuNan uLLaththu * eNmadhiyum kadandhu aNdameedhu pOgi * iruvisumbin Udu pOy ezhundhu *** mElaith thaNmadhiyum kathiravanum thavira Odith * thArakaiyin puRam thadavi appAl mikku * maNmuzhudhum agappaduththu ninRa endhai * malar puraiyum thiruvadi en thalai mElavE *",
            6: "alampurindha nedum thadakkai amarar vEndhan * anjiraippuL thanippAgan avuNarkkenRum * salam purindhu angu aruL illAth thanmaiyALan * thAnugandha UrellAm than thAL pAdi *** nilam parandhu varum kaluzhip peNNai eerththa * neduvEygaL padu muththam undha undhip * pulam parandhu pon viLaikkum poigai vElip * pUnkOvalUr thozhudhum pOdhu nenjE. *",
            7: "vaRpudaiya varai nedum thOL mannar mALa * vadivAya mazhuvEndhi ulagam ANdu * veRpudaiya nedum kadaluL thani vEl uyththa * vELmudhalA venRAnUr vindhai mEya *** kaRpudaiya madakkanni kAval pUNda * kadipozhil sUzh nedu maRugil kamala vEli * poRpudaiya malai araiyan paNiya ninRa * pUngOvalUr thozhudhum pOdhu nenjE *",
            8: "neeragaththAy nedu varaiyin uchchi mElAy * nilAththingaL thuNdaththAy niRaindha kachchi UragaththAy * oNthuRai neer vehkAvuLLAy * uLLuvAr uLLaththAy *** ulagamEththum kAragaththAy kArvAnaththuLLAy kaLvA * kAmarupUngAviriyin then pAl mannu pEragaththAy * pErAdhen nenjin uLLAy * perumAn un thiruvadiyE pENinEnE *",
            9: "vangaththAl mAmaNi vandhundhu munneer mallaiyAy * madhiL kachchi UrAi pErAi * kongaththAr vaLangonRai alangal mArvan * kulavaraiyan madappAvai idappAl koNdAn pangaththAy *** pARkadalAy pArin mElAy * pani varaiyin uchchiyAy pavaLa vaNNA! * enguRRAy emperumAn unnai nAdi * EzhaiyEn inganamE uzhi tharugEnE *",
            10: "pon AnAy pozhil Ezhum kAval pUNda * pugazh AnAy igazhvAya thoNdanEn nAn * en AnAy en AnAy ennal allAl * en aRivan EzhaiyEn *** ulagam Eththum then AnAy vada AnAy kudapAl AnAy * guNapAla madha yAnAy imaiyOrkku enRum mun AnAy * pin AnAr vaNangum sOdhi * thirumUzhik kaLaththAnAy mudhal AnAyE. *",
            11: "pattudukkum ayarththirangum pAvai pENAL * pani nedunkaN neer thathumbap paLLi koLLAL * ettuNaipOdhu en kudankAL irukkakillAL * emperumAn thiruvarangam engE? ennum *** mattuvikki maNi vaNdu muralum kUndhal * mada mAnai idhu seydhAr thammai * meyyE kattuvichchi sol ennach chonnAL nangAy * kadal vaNNar idhu seydhAr kAppAr ArE? *",
            12: "nenjurugik kaNpanippa niRkum sOrum * nedidhuyirkkum uNdaRiyAL uRakkam pENAL * nanjaravil thuyil amarndha nambee ennum * vambArpUm vayalAli maindhA ennum *** anjiRaiya putkodiyE Adum pAdum * aNiryarangam AdudhumO thOzhee ennum * ensiRagin keezh adangAp peNNaip peRREn * irunilaththOr pazhi padaiththEn EpAvame! *",
            13: "kalleduththuk kalmAri kAththAy! enRum * kAmarupUngachchi UrakaththAy! enRum * villiRuththu melliyal thOL thOyndhAy! enRum * vehkAvil thuyilamarndha vEndhE! enRum *** malladarththu mallarai anRattAy! enRum * mAkeeNda kaiththalaththu en myndhA enRum * solleduththuth than kiLiyaich chollE enRu * thuNai mulai mEl thuLi sOrach chOrkinRALE. *",
            14: "muLaikkadhirai kuRunkudiyuL mugilai, * mUvAmUvulagum kadandhappAl mudhAlAy ninRa * aLappariya Aramudhai arangam mEya andhaNanai * andhaNar tham sindhaiyAnai *** viLakkoLiyai maradhakaththaith thiruththANkAvil * vekhAvil thirumAlai pAdakk kEttu * vaLarththadhanAl payan peRREn varugavenRu * madakkiLiyaik kai kUppi vaNanginALE *",
            15: "kalluyarndha nedu madhiL sUzh kachchi mEya kaLirenRum * kadaRkidantha kaniye! enRum * alliyampU malarp poygaip pazhana vEli * aNiyazhundhUr ninRugandha ammAn enRum *** solluyarndha nedu veeNai mulai mEl thAngith * thUmuRuval nagai iRaiyE thOnRa nakku * mel viralgaL sivappeydhath thadavi AngE * menkiLi pOl miga mizhaRRum en pEdhaiyE. *",
            16: "kanRu mEyththu inidhugandha kALAy! enRum * kadipozhil sUzh kaNapuraththu en kaniyE enRum * manRamarak kUththAdi magizhndhAy! enRum * vadathiruvEngadam mEya maindhA! enRum *** venRasurar kulam kaLaindha vEndhE! enRum * viripozhil sUzh thirunaRaiyUr ninRAy enRum * thunRu kuzhal karuniRaththen thuNaiyE! enRum * thuNai mulai mEl thuLi sOrach chOrginRALE *",
            17: "pongAr melliLangkongai ponnE pUppa * porukayaRkaN neerarumbap pOndhu ninRu * sengAla madappuRAvap pedaikkup pEsum * siRukuraluk kudalrugich chindhiththu *** AngE thaNkAlum thaNkudandhai nagarum pAdith * thaN kOvalUr pAdi Adak kEttu * nangAy! nam kudikkidhuvO nanmai? enna * naRaiyUrum pAduvAL navilginRALE. *",
            18: "kAr vaNNam thirumEni kaNNum vAyum * kaiththalamum adiyiNaiyum kamala vaNNam * pArvaNNa madamangai paththar * piththar panimalar mEl pAvaikkup pAvam seydhEn *** ErvaNNa enpEdhai en sol kELAL * emperumAn thiruvarangam engE ennum * neervaNNan neermalaikkE pOvEn ennum * idhuvanRO niRaivazhindhAr niRkumARE *",
            19: "muRRArA vanamulaiyAL pAvai * mAyan moyyagalaththuLLiruppAL ahdhum kaNdum aRRAL * than niRaivazhindhAL AvikkinRAL * aNiyarangam AdudhumO thOzhee! ennum *** peRREn vAychchol iRaiyum pEsak kELAL * pEr pAdith thaN kudanthai nagarum pAdi * poRRAmaraik kayam neerAdap pOnAL * poruvaRRAL en magaL um ponnum ahdhE *",
            20: "thErALum vALarakkan selvam mALath * thennilangai munmalangach chendheeyolgi * pOrALan AyirandhOL vANan mALap * porukadalai araN kadandhu pukku mikka pArALan *** pAridandhu pAraiyuNdu pArumizhndhu pAraLandhu * pArai ANda pErALan * pErOdhum peNNai maNmEl * perundhavaththaL enRallAl pEsalAmE *",
            21: "maivaNNa naRum kunchik kuzhal pin thAzha * magaram sEr kuzhai iru pAdilangi Ada * eyvaNNa venchilaiyE thuNaiyA * ingE iruvarAi vandhAr en munnE ninRar *** kaivaNNam thAmarai vAy kamalam pOlum * kaNNiNaiyum aravindham adiyum ahdhE * avvaNNaththavar nilaimai kaNdum thOzhee! * avarai nAm dhEvarenRu anjinOmE *",
            22: "naivaLamonRArAyA nammai nOkkA * nANinAr pOl iRaiyE nayangaL pinnum * seyvaLavil en manamum kaNNum Odi * emperumAn thiruvadik keezh aNaiya *** ippAl kaivaLaiyum mEkalaiyum kANEn * kaNdEn kanamakarak kuzhai iraNdum nAngu thOLum * evvaLavuNdu emperumAn kOyil enRErku * idhuvanRO? ezhil Ali enRAr thAmE. *",
            23: "uLLUrum sindhai nOy enakke thandhu * en OLi vaLaiyum mAniRamum koNdAr ingE * theLLUrum iLam thengin thERal mAndhich * chElugaLum thiruvarangam nammUr enna *** kaLLUrum painthuzhAy mAlaiyAnaik * kanavidaththil yAn kANban kaNdapOdhu * puLLUrum kaLvA nee pOgEl enban * enRAlum idhu namakkOr pulavi thAnE *",
            24: "iru kaiyil sangivai nillA ellE! pAvam * ilangolineerp perumpauvam maNdiyuNda * peruvayiRRa karumugilE oppar vaNNam * perunthavaththar arunthavaththu munivar sUzha *** oru kaiyil sangorukai maRRAzhi Endhi * ulaguNda peruvAyar ingE vandhu * en porukayarkaN neer arumbap pulavi thandhu * punal arangam UrenRu pOyinArE *",
            25: "minnilangu thiruvuruvum periya thOLum * kari munindha kaiththalamum kaNNum vAyum * thannalarndha naRunthuzhAy malarin keezhE * thAzhndhilangu makaram sEr kuzhaiyum kAtti *** en nalanum en niRaivum en sindhaiyum * en vaLaiyum koNdu ennai ALum koNdu * ponnalarndha narumcherunthip pozhilinUdE * punal arangam UrenRu pOyinArE *",
            26: "thEmaruvu pozhilidaththu malarndha pOdhai * thEnadhanai vAy maduththu un pedaiyum neeyum * pUmaruvi inidhamarndhu poRiyilArndha * aRukAla siRu vaNdE thozhudhEn unnai *** Amaruvi niRai mEyththa amarar kOmAn * aNiyazhundhUr ninRAnukku inRE senRu * neemaruvi anjAdhE ninROr mAdhu * ninnayandhAL enRiRaiyE iyambik kANE *",
            27: "sengAla mada nArAy inRe senRu * thirukkaNNapuram pukken sengaNmAlukku * en kAdhal en thuNaivarkkuraiththiyAgil * idhuvoppadhemakku inbamillai *** nALum paingAnameedhellAm unadhEyAgap * pazhanameen kavarndhuNNath tharuvan * thandhAl ingE vandhinidhirundhun pedaiyum neeyum * irunilaththil inidhinbam eydhalAmE *",
            28: "thennilangai araN sidhari avuNan mALach * chenRulagamUnRinaiyum thirindhOr thErAl * mannilangu bArathaththai mALavUrndha * varaiyuruvin mAkaLiRRaith thOzhee! *** enRan ponnilangu mulaikkuvattil pUttik koNdu * pOgAmai vallEnAyp pulaviyeydhi * ennilangamellAm vandhinbameydha * eppozhudhum ninaindhurugi iruppan nAnE *",
            29: "anRAyar kulamagaLukkaraiyan thannai * alaikadalaik kadaindhadaiththa ammAn thannai * kunRAdha valiyarakkar kOnai mALak * kodunjilaivAych charam thurandhu kulangaLaindhu venRAnaik *** kunReduththa thOLinAnai * virithiraineer viNNagaram maruvinALum ninRAnaith * thaNkudanthaik kidantha mAlai * nediyAnai adinAyEn ninaindhittEnE *",
            30: "minnumA mazhai thavazhum mEga vaNNA * viNNavar tham perumAnE aruLAy enRu * annamAy munivarOdamarar Eththa * arumaRaiyai veLippaduththa ammAn thannai *** mannumA maNimAda mangai vEndhan * mAnavEl parakAlan kaliyan sonna * panniyanUl thamizh mAlai vallAr * thollaip pazhavinaiyai mudhalariya vallAr thAmE *"
        }
    };

    // Non-destructive runtime merging engine
    for (const key in text_bundle_en) {
        window.MARKER_DATABASE[key] = window.MARKER_DATABASE[key] || [];
        for (const p in text_bundle_en[key]) {
            const idx = parseInt(p) - 1;
            window.MARKER_DATABASE[key][idx] = window.MARKER_DATABASE[key][idx] || { p: parseInt(p) };
            window.MARKER_DATABASE[key][idx]['text'] = window.MARKER_DATABASE[key][idx]['text'] || {};
            window.MARKER_DATABASE[key][idx]['text']['en'] = text_bundle_en[key][p];
        }
    }
};