// notes.js - Complete 108 Notes for Ramanuja Nootrandhadhi
const pasuramNotes = {
    "4": "Introductory verse. Amudanar praises Ramanuja for surrendering to Nammalwar (Maaran), the composer of Tiruvaimozhi.",
    "5": "Describes Ramanuja's detachment from those who ignore Lord Ranganatha. He is the ultimate refuge for spiritual seekers.",
    "6": "The joy of reciting Ramanuja's name. It describes how the Acharya provides 'Koor-Iyal-Gnanam' (sharp wisdom) to correct the disciple.",
    "7": "Ramanuja's wisdom is a lamp ('Deepam') that dispels the darkness of the heart and protects from conflicting philosophies.",
    "8": "Ramanuja is the true guru ('Mei-Guru') who clears past karma and showed the path described in the scriptures.",
    "9": "Urges the heart to abandon sensory desires and focus on Ramanuja's names for true happiness.",
    "10": "By gaining the refuge of Ramanuja's feet, the power of ancient karmas to cause fear is completely neutralized.",
    "11": "Ramanuja is the protector of Truth and the 'Aar-Uyir' (Precious Life) for followers of the Alvars.",
    "12": "Ramanuja established the truth of Vedanta, filling the author's mind with philosophical clarity.",
    "13": "Once Ramanuja entered the mind, the author found joy in serving those who love the Acharya (Bhagavata-Seshatvam).",
    "14": "A prayer for Ramanuja to reside in the heart and correct the soul so that the Lord's grace can reach it.",
    "15": "Ramanuja stopped the cycle of karma and gave the shadow of his feet as protection.",
    "16": "The futility of life without serving the devotees of Ramanuja, who destroyed the scriptures of non-believers.",
    "17": "Ramanuja's grace transformed even the stone-hearted into devotees through the power of his holy name.",
    "18": "Ramanuja's mercy granted vast knowledge and made the soul a servant to the Lord's feet.",
    "19": "The author wanders reciting the Tamil hymns of Thirumangai Azhwar, enslaved by Ramanuja's kindness.",
    "20": "Ramanuja speaks to clear our sins; it is a merit to praise the feet of those who love the Azhwars.",
    "21": "Ramanuja grants the wisdom to love the Lord, who is joined by Lakshmi and the Earth Goddess.",
    "22": "Worldly people cannot deceive the devotee now that Ramanuja has placed them among his followers.",
    "23": "Ramanuja leads the devotee to his golden feet and spreads true wisdom across the world.",
    "24": "Ramanuja's grace is like a cooling rain that extinguishes the fire of material desires.",
    "25": "The Acharya's teachings are the only weapon capable of cutting through the dense forest of ignorance.",
    "26": "Praising the compassion of Ramanuja, who looked upon the lowly with the same grace as the high-born.",
    "27": "Ramanuja's presence on earth is compared to the rising sun that makes the lotus of devotion bloom.",
    "28": "Acknowledging Ramanuja as the 'Cloud of Mercy' who turned the author's misery into spiritual bliss.",
    "29": "The heart finds rest only at the feet of Ramanuja, leaving behind the transient pleasures of the world.",
    "30": "Ramanuja is the bridge that carries the soul across the ocean of birth and death.",
    "31": "The glory of those who have surrendered to Ramanuja; they are the true masters of the world.",
    "32": "Ramanuja's eyes, filled with compassion, are the source of all spiritual strength for the devotee.",
    "33": "The author declares that he has no other goal but to serve Ramanuja eternally.",
    "34": "Ramanuja's arrival on earth restored the true meaning of the Vedas which had been distorted.",
    "35": "The sweetness of Ramanuja's name is compared to the most delicious nectar.",
    "36": "Ramanuja's humility, despite his vast knowledge, is a lesson for all spiritual aspirants.",
    "37": "The protection offered by Ramanuja is surer than any worldly shield or fort.",
    "38": "Ramanuja's love for the Alvars' hymns shows the path of devotion through the Tamil language.",
    "39": "The transformation of the world's atmosphere through the presence of Ramanuja and his followers.",
    "40": "Ramanuja is the 'Lion among Ascetics' who defeated the elephant-like pride of false scholars.",
    "41": "The peace that comes from surrendering all burdens to the lotus feet of the Acharya.",
    "42": "Ramanuja's lineage is the golden chain that connects the soul directly to the Supreme Lord.",
    "43": "The author praises the specific attributes of Ramanuja's form that signify his divinity.",
    "44": "Ramanuja is the treasure found by the poor in spirit, providing eternal wealth.",
    "45": "The constant remembrance of Ramanuja's name is the only path to mental purity.",
    "46": "Ramanuja's grace is independent of the devotee's merit, flowing freely to all.",
    "47": "The unity of the devotee's soul with the Acharya's mission.",
    "48": "Ramanuja's mastery over the scriptures was used only to guide others toward the truth.",
    "49": "The author reflects on his own unworthiness and how Ramanuja still chose to save him.",
    "50": "Ramanuja's feet are the only place where the heat of worldly suffering is cooled.",
    "51": "The strength derived from the association with the 'Ramanuja-Sambandhis'.",
    "52": "Ramanuja's life is a living commentary on the message of the Alvars.",
    "53": "The midpoint of the work, reaffirming the total surrender of the author to Ramanuja.",
    "54": "Ramanuja's role in revitalizing the temple rituals and traditions at Srirangam.",
    "55": "The beauty of the relationship between the Guru and the Sishya (disciple).",
    "56": "Ramanuja's patience in correcting the flaws of his followers over many years.",
    "57": "The protection of the tradition through the institutional structures Ramanuja built.",
    "58": "Ramanuja is the 'Udayavar' (the owner), to whom all souls rightfully belong.",
    "59": "The author's gratitude for being born in the same era as Ramanuja.",
    "60": "Ramanuja's teachings on the essential nature of the soul as a servant of the Lord.",
    "61": "The light of Ramanuja's wisdom makes the complex Vedic truths simple to understand.",
    "62": "Ramanuja's compassion for all living beings, reaching even the most forgotten corners.",
    "63": "The stability of the mind that is anchored in the feet of Ramanuja.",
    "64": "Ramanuja's victory over the internal enemies of lust, anger, and greed.",
    "65": "The Acharya's feet are the source of all auspiciousness (Mangalam).",
    "66": "Ramanuja's unwavering focus on the Lord of Srirangam as the ultimate goal.",
    "67": "The legacy of Ramanuja that will continue to guide souls for generations.",
    "68": "Ramanuja's ability to turn even the most worldly minds toward spiritual inquiry.",
    "69": "The author compares Ramanuja to a mother who cares for her child's spiritual growth.",
    "70": "Ramanuja's rejection of external rituals that lack internal devotion.",
    "71": "The power of Ramanuja's gaze to melt the hardest of hearts.",
    "72": "Ramanuja is the gardener who tends to the forest of the Alvars' hymns.",
    "73": "The absolute certainty of liberation for those who have Ramanuja as their Acharya.",
    "74": "Ramanuja's deep connection to the 'Tiruppavai' of naachiyar.",
    "75": "The Acharya as the ultimate mediator between the soul and the Lord.",
    "76": "Ramanuja's humility in crediting all his successes to his own teachers.",
    "77": "The fragrance of Ramanuja's virtues spreads in all directions.",
    "78": "The author describes the physical marks of Ramanuja that indicate his spiritual authority.",
    "79": "Ramanuja's role in preserving the Tamil Divya Prabandham for posterity.",
    "80": "The joy of those who hear the stories of Ramanuja's life and miracles.",
    "81": "Ramanuja's ability to provide the correct interpretation of the Brahma Sutras.",
    "82": "The Acharya's feet are the refuge for those who have no other support.",
    "83": "Ramanuja's constant engagement in the service of the Lord and his devotees.",
    "84": "The author praises the city of Srirangam as the center of Ramanuja's activity.",
    "85": "Ramanuja's teachings on the importance of 'Kainkaryam' (eternal service).",
    "86": "The Acharya's role in uniting different schools under Vishishtadvaita.",
    "87": "Ramanuja's compassion for those who have committed great sins.",
    "88": "The light of the Acharya's wisdom dispels the 'Kali' (dark age) influence.",
    "89": "Ramanuja is the captain of the ship leading souls to the 'Vaikuntha' shore.",
    "90": "The author's prayer to never be separated from the company of Ramanuja's devotees.",
    "91": "Ramanuja's role in purifying the holy places and rivers of the land.",
    "92": "The Acharya's mastery over both the Sanskrit Vedas and the Tamil hymns.",
    "93": "Ramanuja's constant meditation on the feet of the Alvars.",
    "94": "The author reflects on the change in his own nature after meeting the Acharya.",
    "95": "Ramanuja's grace is the only shield against the arrows of material desire.",
    "96": "The Acharya's role in establishing the 'Nityasurikas' path on earth.",
    "97": "Ramanuja's humility in considering himself the least among the Lord's servants.",
    "98": "The power of the 'Ramanuja Mantra' to grant all spiritual desires.",
    "99": "Ramanuja's role in protecting the 'Sri Sampradaya' from external threats.",
    "100": "The author praises the devotees of Ramanuja as being equal to the Acharya himself.",
    "101": "Ramanuja's feet are the only destination for the soul's journey.",
    "102": "The Acharya's role in providing the true meaning of the Charama Shloka.",
    "103": "The completion of the hundredth verse, marking a major milestone.",
    "104": "Ramanuja's influence on the hearts of even the birds and animals of Srirangam.",
    "105": "The Acharya's role in ensuring the message of the Alvars reaches everyone.",
    "106": "Ramanuja's constant state of bliss in the service of the Lord.",
    "107": "The author's final plea for the Acharya to never let him fall back into ignorance.",
    "108": "Today Ramanuja has joyfully made my heart his abode, washing away the false impressions of other paths.",
    "109": "O Ramanuja of joyful character! Even if I suffer through endless births, let me remain a servant to your devotees.",
    "110": "Ramanuja's grace has enslaved me to his feet, preventing me from turning to other gods and providing the 'medicine' for karma.",
    "111": "Let us praise naachiyar and the Lord of Srirangam, while the glorious feet of Ramanuja reside forever upon our heads."
};
