window.MARKER_DATABASE = window.MARKER_DATABASE || {};
window.mergeLanguageTexts = function () {
    const text_bundle_en = {
        '4TA.0.steps': {
            1: "nArayaNan padaiththAn nAnmuganai * nAnmuganukku ErAr Sivan piRandhAn ennum sol *** sIrAr mozhi seppi vAzhalAm nenjamE!*  moy pU mazhisaip parAn adiyE vAzhththu",
        },
        '4TA.1.steps':
        {
            1: " *nAnmuganai * nArAyaNan padaiththAn * nAnmuganumthAnmugamAy *  sankaranaiththAn padaiththAn *** yAnmugamAyandhAdhi mElittu *  aRiviththEn AzhporuLai * sindhAmal koNminIr thErndhu",
            2: "thErungAl dhEvan *  oruvanE enRuraippar * Arum aRiyAr avan perumai *** OrumporuL mudivum iththanaiyE *  eththavam seydhArkkum * aruL mudivadhu AzhiyAn pAl",
            3: "pAlil kidandhadhuvum *  paNdarangam mEyadhuvum * Alil thuyinRadhuvum AraRivAr? *** gyAlaththoruporuLai * vAnavar tham meypporuLai * appilaruporuLai yAn aRindhavARu",
            4: "ARu sadaik karandhAn *  aNdarkOn thannOdum * kURudaiyan enbadhuvum koLgaiththE *** vERoruvanillAmai * ninRAnai emmAnai * epporutkumsollAnaich chonnEn thoguththu",
            5: "thoguththa varaththanAyth * thOlAdhAn mArvam * vagirththa vaLaiyugirththOL mAlE! *** ugaththiloru nAnRu nI uyarththi *  uLvAngi nIyE * arunAngum AnAy aRi    ",
            6: "aRiyAr samaNar * ayarththAr bavuththar * siRiyAr sivappattAr seppil *** veRiyAyamAyavanai mAlavanai * mAdhavanai EththAdhAr * InavarE AdhalAl inRu    ",
            7: "inRAga * nALaiyEyAga *  inichchiRidhuninRAga *  ninnaruL enpAladhE *** nanRAganAnunnai * anRi ilEn kANdAy * nAraNanE!nI ennai anRi ilai    ",
            8: "ilai thuNai maRRen nenjE! *  Isanai venRa * silai koNda sengaNmAl sErA *** kulai koNdaIraindhalaiyAn * ilangaiyai Idazhiththa * kUrambanallAl kuRai    ",
            9: "kuRai koNdu nAnmugan * kuNdigai nIr peydhu * maRai koNda mandhiraththAl vAzhththi *** kaRaikoNdakaNdaththAn * senni mEl ERak kazhuvinAn * aNdaththAn sEvadiyai Angu    ",
            10: "AngAravAram * adhu kEttu * azhal umizhumpUngAraravaNaiyAn ponmEni ***yAngANavallamE allamE? *  mAmalarAn vAr sadaiyAn * vallarE allarE ? vAzhththu",
            11: "vAzhthuga vAy *  kANga kaN kEtka sevi * magudamthAzhththi * vaNangumingaL thaNmalarAl *** sUzhththathuzhAy mannu nINmudi * en thollai mAl thannai * vazhA vaN kai kUppi madhiththu",
            12: "madhiththAy pOy nAngin * madhiyAdhAr pOy vIzha * madhiththAy madhikOL viduththAy *** madhiththAymadukkidandha *  mA mudhalai kOL viduppAn * AzhividaRkiraNdum pOyiraNdin vIdu",
            13: "vIdAkkum *  peRRi aRiyAdhu * mey varuththikkUdAkki *  ninRuNdu koNduzhalvIr! ***vIdAkkummeypporuLdhAn *  vEdha mudhaRporuLdhAn * viNNavarkkunaRporuLdhAn nArAyaNan",
            14: "nArAyanan ennai ALi * naragaththuchchErAmal * kAkkum thirumAL *** than pErAnApEsappeRAdha * piNachchamayar pEsakkEttu * AsaippattAzhwAr palar    ",
            15: "pala dhEvar Eththap *  padi kadandhAn pAdham * malarERa vittiRainji vAzhththa - valar Agil * mArkkaNdan kaNda vagaiyE *  varum kaNdIr * nIrkkaNdan kaNda nilai",
            16: "nilai mannum en nenjam * annAnRu * dhEvarthalai mannar *  thAmE mARRAga *** pala mannarpOrmALa * vengadhirOn mAyappozhil maRaiya * thErAzhiyAl maRaiththArAl",
            17: "Ala nizhaRkIzh * aRaneRiyai *  nAlvarkkumElai yugaththuraiththAn *  meyththavaththOn ***gyAlamaLandhAnai * AzhikkidandhAnai * AlmElvaLarndhAnaith thAn vaNangumARu",
            18: "mARAya dhAnavanai * vaLLugirAl * mArviraNdukURAgak * kIRiya kOLariyai *** vERAgaEththiyiruppArai * vellumE * maRRavaraichchAththiyiruppar thavam",
            19: "thavam seydhu * nAnmuganAl peRRa varaththai * avam seydha AzhiyAn anRe *** uvandhemmaikkAppAy nI * kAppadhanai AvAy nI * vaikundhamIppAyum evvuyirkkum nI",
            20: "nIyE ulagellAm * ninnaruLE niRpanavum * nIyE thavaththEva dhEvanum *** nIyEerisudarum mAl varaiyum *  endhisaiyum * aNdaththuirusudarum Aya ivai    ",
            21: "ivaiyA ! pilavAy * thiRandherikANRa * ivaiyA ! eri vattak kaNgaL *** ivaiyA!eri pongik kAttum *  imaiyOr perumAn * ari pongik kAttum azhagu",
            22: "azhagiyAn thAnE *  ari uruvan thAnE * pazhagiyAn thALE paNimin *** kuzhaviyAyththAnEzh ulagukkum * thanmaikkum thanmaiyanE * mInAy uyiraLikkum viththu",
            23: "viththum ida vENdungolO? *  vidaiyadarththa * paththi uzhavan pazham punaththu *** moyththezhundhakAr mEgam anna *  karumAl thirumEni * nIr vAnam kAttum nigazhndhu",
            24: "nigazhndhAy * pAl pon pasuppuk *  kAr vaNNam nAngumigazhndhAy *  iruvaraiyum vIyap - pugazhndhAy * sinappOrch chuvEdhanaich * chEnApadhiyAy * manappOr mudikkum vagai",
            25: "vagaiyAl madhiyAdhu *  maNkoNdAy *  maRRumvagaiyAL * varuvadhu onRuNdE *** vagaiyAlvayiram kuzhaiththuNNum * mAvali thAnennum * vayira vazhakkozhiththAy maRRu",
            26: "maRRuth thozhuvAr * oruvaraiyum yAn inmai * kaRRaichchadaiyAn karikkaNdAy ***eRRaikkumkaNdukoL kaNdAy * kadalvaNNA ! * yAnunnaikkaNdu koLgiRkumARu",
            27: "mAl thAn pugundha *  mada nenjam * maRRadhuvumpERAgak *  koLvanO? pEdhaigAL! *** nIRAdiththAn kANa mAttAdha *  thAragalach chEvadiyai * yAn kANa vallERkidhu",
            28: "idhuvilangai Idazhiyak *  kattiya sEthu * idhuvilangu vAliyai vIzhththadhuvum *** idhuvilangaithAnodunga vil nudangath *  thaNdArirAvaNanai * Unodunga eydhAn ugappu",
            29: "ugappuruvam thAnE *  oLiyuruvam thAnE * magappuruvam thAnE madhikkil *** migappuruvamonRukkonRu * OsanaiyAnvIzha *  oru kaNaiyAlanRikkoNdu eydhAn avan",
            30: "avan ennai ALi * arangaththu arangil * avan ennai eydhAmal kAppAn *** avan ennadhuuLLaththu * ninRAn irundhAn kidakkumE * veLLaththaravaNaiyin mEl",
            31: "mEl nAnmugan * aranaiyitta vidu sAbam * thAn nAraNan ozhiththAn thAragaiyuL ***vAnOrperumAnai * EththAdha pEygAL! * piRakkumkarumAyam pEsil kadhai",
            32: "kadhaip poruLdhAn *  kaNNan thiruvayiRRinuLLa * udhaippaLavu pOdhu pOkkinRi ***vadhaipporuLdhAnvAyndha guNaththup * padAdhadhu adaiminO * Ayndha guNaththAn adi",
            33: "adichchagadam sAdi * aravAtti * Anaipidiththosiththup * pEymulai nanjuNdu *** vadippavaLavAippinnaith thOLikkA * vallERReruththiRuththu * kOppinnumAnAn kuRippu",
            34: "kuRippenakku * kOttiyUr mEyAnai Eththa * kuRipppenakku nanmai payakka ***veRuppanO?vEngadaththu mEyAnai * mey vinai nOy eydhAmal * thAngadaththum thanmaiyAn thAL",
            35: "*thALAl ulagam * aLandha asaivE kol? * vALA kidandharuLum vAy thiRavAn *** nILOdhamvandhalaikkum mAmayilai *  mAvallikkENiyAn * aindhalai vAy nAgaththaNai",
            36: "nAgaththaNaik kudandhai *  vehkAth thiruvevvuL * nAgaththaNai arangam pEranbil *** nAgath thaNaip pARkadal kidakkum *  Adhi nedumAl * aNaippAr karuththan AvAn    ",
            37: "vAnulavau thIvaLi * mAkadal mAporuppu * thAnulavu vengadhirum thaNmadhiyum *** mEnilavukoNdal peyarum *  dhisaiyettum sUzhchchiyum * aNdandhirumAl agaippu",
            38: "agaippil manisarai * ARu samayampugaiththAn * porukadal neervaNNan *** ugaikkumEleththEvar vAlAttum * evvARu seygaiyum * appOdhu ozhiyum azhaippu",
            39: "azhaippan * thiruvEngadaththAnaik kANa * izhaippan * thirukkUdal kUda ***mazhaippEraruvi * maNivaranRi vandhizhiya * yAnaiveruvi aravondungum veRpu    ",
            40: "veRpenRu *  vEngadam pAdinEn *  vIdAkkiniRkinREn * ninRu ninaikkinREn *** kaRkinRanUlvalaiyil pattirundha *  nUlAttik kELvanAr * kAlvalaiyil pattirundhEn kAN    ",
            41: "kANal uRuginREn * kallaruvi muththudhira * ONa vizhavil oli adhira *** pENivaru vEngadavA! *  en uLLam pugundhAy * thiruvEngadam adhanaich chenRu",
            42: "senRu vaNanguminO *  sENuyar vEngadaththai * ninRu vinaikedukkum nIrmaiyAl *** enRumkadikkamala nAnmuganum *  kaN mUnRaththAnum * adikkamalam ittEththum angu",
            43: "mangul thOy senni * vadavEngadaththAnai * kangul pugundhArgaL *  kAppaNivAn *** thingaLsadaiyERa vaiththAnum *  thAmarai mElAnum * kudaiyERath thAnguviththuk koNdu",
            44: "koNdu kudangAL * mEl vaiththa kuzhaviyAy * dhaNdavarakkan thalai thALAl - paNdeNNip * pOm kumaran niRkum * pozhil vEngada malaikkE * pOm kumarar uLLIr purindhu",
            45: "purindhu malarittup *  puNdarIgappAdham * parindhu padu kAdu niRpa *** therindhengumthAnOngi niRkinRAn * thaNNaruvi vEngadamE * vAnOrkkum maNNOrkkum vaippu",
            46: "vaippan maNiviLakkA * mAmadhiyai * mAlukkenRueppozhudhum *  kai nIttum yAnaiyai *** eppAdumvEduvaLaikkak * kuRavar villedukkum vEngadamE * nAdu vaLaiththu AdudhumEl nanRu",
            47: "nanmaNi vaNNanUr *  ALiyum kOLariyum * ponmaNiyum muththamum pUmaramum *** panmaNi nIrodu porudhuruLum * kAnamum vAnaramum * vEdumudai vEngadam",
            48: "vEngadamE *  viNNOr thozhuvadhuvum * meymmaiyAlvEngadamE * mey vinai nOy thIrppadhuvum *** vEngadamEdhAnavarai vIzhath * thannAzhip padai thottu * vAnavaraik kAppAn malai",
            49: "malaiyAmaimEl vaiththu * vAsugiyaichchuRRi * thalaiyAmai thAnoru kai paRRi ***alaiyAmalpIRak kadaindha * perumAL thirunAmam * kURuvadhE yAvarkkum kURRu",
            50: "kURRamum sArA * kodu vinaiyum sAra * thImARRamum sArA vagai aRindhEn *** ARRanggaraikkidakkum *  kaNNan kadal kidakkum * mAyanuraikkidakkum uLLaththenakku",
            51: "enakkAvAr Ar oruvarE? * emperumAnthanakkAvAn * thAnE maRRallAl *** punakkAyAvaNNanE! * unnaip piRar aRiyAr *  enmadhikkuviNNellAm uNdo vilai ?   ",
            52: "vilaikkAtpaduvar *  visAdhiyERRuNbar * thalaikkAtbali thirivar thakkOr ***mulaikkAlvidamuNda vEndhanaiyE * vERA EththAdhAr * kadamuNdAr kallAdhavar",
            53: "kallAdhavar ilangai kattazhiththa *  kAguththanallAl *  oru dheyvam yAnilEn ***pollAdhadhEvaraith *  thEvarallAraith * thiruvillAththEvarai thERElmin dhEvu",
            54: "dhEvarAy *  niRkum aththEvum * aththEvarilmUvarAy niRkum * mudhupuNarppum *** yAvarAyniRkinRadhellAm * nedumAl enROrAdhAr * kaRkinRadhellAm kadai",
            55: "kadai ninRu amarar kazhal thozhudhu *  nALumidai ninRa * inbaththarAvar *** pudai ninRanIrOdha mEni * nedumAlE! * nin adiyaiyArOdha vallAr avar?   ",
            56: "avar ivar enRillai * anangavEL thAdhaikku * evarum edhirillai kaNdIr *** uvarikkadal nanjamuNdAn kadanenRu *  vANaRkuudaninRu thORRAn orungu",
            57: "orungirundha nalvinaiyum *  thIvinaiyum AvAn * perungurundham sAyththavanE pEsil ***marungirundhavAnavardhAm dhAnavardhAm *  thAragaidhAn * ennenjamAnavardhAn allAdhadhen ?   ",
            58: "ennenjamEyAn *  iruL nIkki empirAn * mannanja munnorunAL maNNaLandhAn *** ennenjamEyAnai *  illA vidai ERRAn * vevvinai thIrththuAyAnukkAkkinEn anbu",
            59: "anbAvAy *  AramudhamAvAy * adiyEnukkuinbAvAy *  ellAmum nIyAvAy *** pon pAvaikELvA ! * kiLaroLi en kEsavanE! * kEdinRiALvAykku adiyEn nAn AL",
            60: "AL pArththu uzhitharuvAy *  kaNdukoL enRu * ninthAL pArththu uzhi tharuvEn thanmaiyai ***kEtpArkkuarum poruLAy *  ninRa aranganE! * unnaivirumbuvadhE viLLEn manam",
            61: "manakkEdham sArA * madhusUdhan thannai * thanakEdhAn thanjamAkkoLLil *** enakkEdhAninRonRi ninRulagai *  EzhANai OttinAn * senRonRi ninRa thiru    ",
            62: "thiru ninRa pakkam *  thiRavidhenRu OrAr * karu ninRa kallArkku uraippar *** thiruvirundhamArvan *  sirIdharan than vaNdulavu thaNduzhAy * thAr thannaich chUdith thariththu",
            63: "thariththirundhEnAgavE *  thArA gaNappOr * viriththuraiththa vennAgaththu unnai *** theriththezhudhivAsiththum kEttum * vaNangi vazhipattum * pUsiththum pOkkinEn pOdhu",
            64: "pOdhAna *  vittiRainji EththuminO * ponmagarakkAdhAnai *  AdhipperumAnai *** nAdhAnainallAnai nAraNanai *  nammEzh piRappaRUkkumsollAnaich * cholluvadhE sUdhu",
            65: "sUdhAvadhu ennenjaththu eNNinEn * sol mAlaimAdhAya * mAlavanai mAdhavanai ***yAdhAnumvallavA * sindhiththu iruppERku * vaigundhaththuillaiyO solleer idam?       ",
            66: "idam Avadhu * ennenjam inRellAm * paNdupadanAgaNai * nediya mARku *** dhidamAgavaiyEn * madhi sUdi thannOdu * ayanai nAnvaiyEn AtcheyyEn valam    ",
            67: "valamAga *  mAttAmai thAnAga * vaigalkulamAga *  kuRRandhAnAga *** nalamAganAraNanai nApadhiyai * gyAnapperumAnaisIraNanai Eththum thiRam",
            68: "thiRambEnmin kaNdIr *  thiruvadi than nAmam * maRandhum puRam thozhA mAndhar *** iRainjiyumsAdhuvarAyp * pOmingaL enRAn * namanum thanthUdhuvaraik kUvich chevikku",
            69: "sevikkinabamAvadhum *  sengaNmAl nAmam * puvikkum puviyadhuvE kaNdIr ***kavikkuniRaiporuLAy * ninRAnai nErppattEn * paRkkilmaRaipporuLum aththanaiyE thAn",
            70: "thAn oruvanAgith *  tharaNi idandheduththu * EnoruvanAy eyiRRil thAngiyadhum *** yAn oruvan * inRAvaRiginREn * allEn iru nilaththaichchenRAngu adippaduththa sEy",
            71: "sEyan aNiyan * siRiyan migapperiyan * Ayan thuvaraikkOnAy ninRa - mAyan * anRuOdhiya *  vAkkadhanaik kallAr * ulagaththilEdhilarAm mey gyAnamil",
            72: "illaRam illEl * thuRavaRam illennum * sollaRam allanavum sollalla ***nallaRamAvanavum * nAlvEdha mAththavamum * nAraNanEAvadhu Idhu anRu enbAr Ar?",
            73: "ArE aRivAr ? * anaiththulagum undhumizhndha * pErAzhiyAn than perumaiyai ***kAr seRindhakaNdaththAn * eNkaNNAn kANAn * avan vaiththapaNdaiththAnaththin padhi",
            74: "padhippagaigyarkku ARRAdhu *  pAy thirai nIrppAzhi * madhiththadaindha vALaravam thannai *** madhiththavanthanvallAgath thERRiya * mAmEni mAyavanai * allAdhonRu EththAdhennA",
            75: "nAkkoNdu *  mAnidam pAdEn *  nalamAgaththIkkoNda *  senjadaiyAn senRu *  enRum - pUkkoNduvallavAR * Eththa magizhAdha * vaigundhachchelvanAr sEvadimEl pAttu    ",
            76: "pAttum muRaiyum *  padu kadhaiyum palporuLum * Ittiya thIyum iruvisumbum *** kEttamanuvum * surudhi maRai nAngum * mAyanthanamAyaiyil pattadhaRpu    ",
            77: "thaRpennaith thAnaRIyAnElum * thadangadalaikkaRkoNdu thUrththa kadal vaNNan *** eRkoNdavevvinaiyum nInga * vilangA manam vaiththAn * evvinaiyum mAyumAl kaNdu    ",
            78: "kaNdu vaNanginarkku * ennAngol ? * kAmanudalkoNda *  thavaththARku umai uNarththa *** vaNdalambumthAralangal nINmudiyAn * than peyarE kEttirundhu * anguAralangal AnamaiyAl Ayndhu",
            79: "Ayndhu koNdu *  AdhipperumAnai * anbinAlvAyndha *  manaththiruththa vallArgaL ***Eyndha thammeykundhamAga * virumbavarE *  thAmum thamvaigundham kANbAr viraindhu",
            80: "virandhadaimin mElorunAL *  veLLam parakkak * karandhulagam kAththaLiththa kaNNan *** parandhulagam * pAdina Adina kEttup * padunaragamvIdina vAsaR kadhavu    ",
            81: "kadhavu manam enRum *  kANalAm enRum * kudhaiyum vinaiyAvi thIrndhEn *** vidhaiyAganaRRamizhai viththi * en uLLaththai nI viLaiththAy * kaRRa mozhiyAgik kalandhu    ",
            82: "kalandhAn ennuLLaththuk *  kAmavEL thAdhai * nalandhAnum IdhoppadhuNdE? *** alarndhalargaLittEththum * Isanum nAnmuganum * enRivargaLvittEththa mAttAdha vEndhu    ",
            83: "vEndharAy viNNavarAy *  viNNAgith thaNNaLiyAy * mAndharAy mAdhAy maRRellAmAy ***sArndhavarkkuththan ARRAn nEmiyAn * mAlvaNNan thAn kodukkum * pinnAl thAn seyyum pidhir    ",
            84: "pidhirum manam ilEn * pigygyagan thannoduedhirvan * avan enakku nErAn ***adhirumkazhaRkAla mannanaiyE *  kaNNanaiyE * nALumthozhum kAdhal pUNdEn thozhil",
            85: "thozhil enakkuth * thollaimAl than nAmam Eththa * pozhudhu enakku maRRadhuvE pOdhum *** kazhi sinaththavallALan * vAnarar kOn vAli madhanazhiththa * villALan nenjaththuLan",
            86: "uLan kaNdAy nannenjE! *  uththaman enRumuLan kaNdAy * uLLuvAr uLLaththu - uLan kaNdAy * thannoppAn thAnAy *  uLan kAn thamiyERku * ennoppArkku Isan imai",
            87: "imayap perumalai pOl * indhiranArkkitta * samaya virundhu uNdu Ar kAppAr? *** samayangaLkaNdAn avai kAppan * kArkkaNdan nAnmuganOdu * uNdAN ulagOdu uyir    ",
            88: "uyir koNdu udalozhiya * Odum pOdhOdi * ayarvenRa thIrppAn pEr pAdi ***seyal thIrachChindhiththu *  vAzhvArE vAzhvAr * siRu samayappandhanaiyAr vAzhvEl pazhudhu",
            89: "pazhudhAgAdhonRaRindhEn *  pARkadalAn pAdham * vazhuvA vagai ninaindhu vaigal - thozhuvArai * kaNdiRainji vAzhvAr * kalandha vinai keduththu * viN thiRandhu vIRRiruppAr mikku",
            90: "vIRRirundhu * viNNALa vENduvAr * vEngadaththAnpAl thirundha vaiththArE panmalargaL *** mEl thirundhavAzhvAr * varumadhi pArththu anbinarAy * maRRavarkkEthAzhvAy iruppAr thamar    ",
            91: "thamarAvAr yAvarkkum *  thAmarai mElArkkum * amararkkum AdaravArththARkum *** amarargaLthAL thAmarai * malargaLittiRainji * mAlvaNNanthAL thAmarai adaivOm enRu",
            92: "enRum maRandhaRiyEn * en nenjaththE vaiththu * ninRum irundhum nedumAlai *** enRumthiruvirundha mArban * sirIdharanakku ALAy * karu irundha nAL mudhalAk kAppu",
            93: "kAppu maRandhaRiyEn * kaNNanE enRiruppan * Appangazhiyavum palluyirkkum ***AkkaikoduththaLiththa * kOnE! guNaparanE! *  unnaividhath thuNiyAr mey theLindhAr thAm",
            94: "mey theLindhAr enseyyAr? * vERAnAr nIRAga * kai theLindhu kAttik kaLappaduththu ***paitheLindhapAmbin aNaiyAy! *  aruLAy adiyERku * vEmbum kaRiyAgum EnRu    ",
            95: "*EnREn adimai * izhindhEn piRappidumbai * AnREn amararkku amarAmai *** AnREnkada nAdum maNNAdum *  kaivittu *  mElaiida nAdu kANa ini    ",
            96: "*iniyaRindhEn * IsaRkum nAnmugaRkum dheyvam * iniyaRindhEn emperumAn! unnai *** iniyaRindhEnkAraNan nI kaRRavai nI * kaRpavai nI * naRkirisainAraNan nI nangaRindhEn nAn",


        },
    };

    // Non-destructive runtime merging engine
    for (const key in text_bundle_en) {
        window.MARKER_DATABASE[key] = window.MARKER_DATABASE[key] || [];
        for (const p in text_bundle_en[key]) {
            const idx = parseInt(p) - 1;
            window.MARKER_DATABASE[key][idx] = window.MARKER_DATABASE[key][idx] || { p: parseInt(p) };
            window.MARKER_DATABASE[key][idx]['text'] = window.MARKER_DATABASE[key][idx]['text'] || {};
            window.MARKER_DATABASE[key][idx]['text']['en'] = text_bundle_en[key][p];
        }
    }
};
